### ISSUE TITLE
[BUG] json-mapper: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Tarrowren** [TypedProject/tsed#1063]
koa.js
version:6.3.4

```javascript
  return await getConnection()
            .createQueryBuilder()
            .select("menu")
            .from(Menu, "menu")
            .leftJoinAndSelect("menu.subMenus", "subMenu")
            .leftJoinAndSelect("subMenu.subItems", "subItem")
            .orderBy({
                "menu.index": "ASC",
                "subMenu.index": "ASC",
                "subItem.index": "ASC",
            })
            .getMany();
```
```json
{
    "name": "RangeError",
    "message": "Maximum call stack size exceeded",
    "status": 500,
    "errors": [],
    "stack": "RangeError: Maximum call stack size exceeded\n    at Object.getJsonMapperTypes (X\\node_modules\\@tsed\\json-mapper\\lib\\domain\\JsonMapperTypesContainer.js:11:5)\n    at serialize (X\\node_modules\\@tsed\\json-mapper\\lib\\utils\\serialize.js:65:78)\n    at JsonMapperContext.next [as _next] (X\\node_modules\\@tsed\\json-mapper\\lib\\utils\\serialize.js:86:25)\n    at JsonMapperContext.next (X\\node_modules\\@tsed\\json-mapper\\lib\\domain\\JsonMapperContext.js:13:21)\n    at X\\node_modules\\@tsed\\json-mapper\\lib\\components\\ArrayMapper.js:16:54\n    at Array.map (<anonymous>)\n    at ArrayMapper.serialize (X\\node_modules\\@tsed\\json-mapper\\lib\\components\\ArrayMapper.js:16:32)\n    at serialize (X\\node_modules\\@tsed\\json-mapper\\lib\\utils\\serialize.js:94:27)\n    at JsonMapperContext.next [as _next] (X\\node_modules\\@tsed\\json-mapper\\lib\\utils\\serialize.js:86:25)\n    at JsonMapperContext.next (X\\node_modules\\@tsed\\json-mapper\\lib\\domain\\JsonMapperContext.js:13:21)\n    at X\\node_modules\\@tsed\\json-mapper\\lib\\components\\ArrayMapper.js:16:54\n    at Array.map (<anonymous>)\n    at ArrayMapper.serialize (X\\node_modules\\@tsed\\json-mapper\\lib\\components\\ArrayMapper.js:16:32)\n    at serialize (X\\node_modules\\@tsed\\json-mapper\\lib\\utils\\serialize.js:94:27)\n    at JsonMapperContext.next [as _next] (X\\node_modules\\@tsed\\json-mapper\\lib\\utils\\serialize.js:86:25)\n    at JsonMapperContext.next (X\\node_modules\\@tsed\\json-mapper\\lib\\domain\\JsonMapperContext.js:13:21)"
}
```
but it is ok in this way
```javascript
   let a = await getConnection()
            .createQueryBuilder()
            .select("menu")
            .from(Menu, "menu")
            .leftJoinAndSelect("menu.subMenus", "subMenu")
            .leftJoinAndSelect("subMenu.subItems", "subItem")
            .orderBy({
                "menu.index": "ASC",
                "subMenu.index": "ASC",
                "subItem.index": "ASC",
            })
            .getMany();
        return JSON.stringify(a);
```

**Comment by Romakita** [comment]
Hello @Romakita 

Your example isn’t pretty simple. I won’t be able to reproduce the issue because it depend on the database structure and the used orm. Can you give me a reproducible example just with the returned data only or give me more details. 

See you
Romain

**Comment by Tarrowren** [comment]
typeorm
oracle
```typescript
@Entity()
export class Menu {
    @PrimaryGeneratedColumn("uuid")
    @Property()
    id: string;

    @Column()
    @Required()
    label: string;

    @OneToMany(() => SubMenu, (subMenu) => subMenu.menu)
    @Property()
    subMenus: SubMenu[];
}


@Entity()
export class SubMenu {
    @PrimaryGeneratedColumn("uuid")
    @Property()
    id: string;

    @Column()
    @Required()
    label: string;

    @ManyToOne(() => Menu, (menu) => menu.subMenus, {
        onDelete: "CASCADE",
    })
    @Required()
    menu: Menu;

    @OneToMany(() => SubItem, (subItem) => subItem.subMenu)
    @Property()
    subItems: SubItem[];
}

@Entity()
export class SubItem {
    @PrimaryGeneratedColumn("uuid")
    @Property()
    id: string;

    @Column()
    @Required()
    label: string;

    @ManyToOne(() => SubMenu, (subMenu) => subMenu.subItems, {
        onDelete: "CASCADE",
    })
    @Required()
    subMenu: SubMenu;
}

```

**Comment by Romakita** [comment]
Ok thanks. Can you give the data outputed by the json.stringify please.

**Comment by Romakita** [comment]
As I see, your models are badly declared. All collection aren’t correctly decorated. Keep in mind, use typeorm decorators isn’t enough. Ts.ED need also to decorate collection with the appropriate decorators.

To declare a collection you have to use ˋ@CollectionOf` Instead of `@Property`.

**Comment by Tarrowren** [comment]
Thank you, my problem is solved.😀
