### ISSUE TITLE
[BUG] Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Tarrowren** [TypedProject/tsed#1096]
Replay: 
koa.js/ typeorm/ oracle
create a new project
```typescript
@Entity()
export class TTT {
    @PrimaryGeneratedColumn("uuid")
    @Property()
    id: string;

    @Column()
    @Required()
    name: string;
}
```
```typescript
@Controller("/hello-world")
export class HelloWorldController {
    @Get("/")
    async get(): Promise<DeleteResult> {
        return await getConnection()
            .createQueryBuilder()
            .delete()
            .from(TTT)
            .where("1 = 1")
            .execute();
    }
}
```
error:
```json
{
    "name": "TypeError",
    "message": "Cannot read property 'prototype' of undefined",
    "status": 500,
    "errors": [],
    "stack": "TypeError: Cannot read property 'prototype' of undefined\n    at Object.getClass (E:\\code\\tsed-test\\node_modules\\@tsed\\core\\src\\utils\\ObjectUtils.ts:37:17)\n    at Function.hasOwn (E:\\code\\tsed-test\\node_modules\\@tsed\\core\\src\\class\\Metadata.ts:319:40)\n    at Store._storeGet (E:\\code\\tsed-test\\node_modules\\@tsed\\core\\src\\class\\Store.ts:219:21)\n    at E:\\code\\tsed-test\\node_modules\\@tsed\\core\\src\\class\\Store.ts:43:23\n    at new Store (E:\\code\\tsed-test\\node_modules\\@tsed\\core\\src\\class\\Store.ts:49:7)\n    at Function.from (E:\\code\\tsed-test\\node_modules\\@tsed\\core\\src\\class\\Store.ts:66:12)\n    at Function.from (E:\\code\\tsed-test\\node_modules\\@tsed\\schema\\src\\domain\\JsonEntityStore.ts:231:25)\n    at E:\\code\\tsed-test\\node_modules\\@tsed\\json-mapper\\src\\utils\\serialize.ts:31:41\n    at Array.forEach (<anonymous>)\n    at getSchemaProperties (E:\\code\\tsed-test\\node_modules\\@tsed\\json-mapper\\src\\utils\\serialize.ts:30:21)\n    at classToPlainObject (E:\\code\\tsed-test\\node_modules\\@tsed\\json-mapper\\src\\utils\\serialize.ts:56:10)\n    at Object.serialize (E:\\code\\tsed-test\\node_modules\\@tsed\\json-mapper\\src\\utils\\serialize.ts:146:33)\n    at ConverterService.serialize (E:\\code\\tsed-test\\node_modules\\@tsed\\common\\src\\mvc\\services\\ConverterService.ts:65:12)\n    at PlatformKoaHandler.flush (E:\\code\\tsed-test\\node_modules\\@tsed\\common\\src\\platform\\services\\PlatformHandler.ts:236:69)\n    at PlatformKoaHandler.flush (E:\\code\\tsed-test\\node_modules\\@tsed\\platform-koa\\src\\services\\PlatformKoaHandler.ts:54:18)\n    at PlatformKoaHandler.onSuccess (E:\\code\\tsed-test\\node_modules\\@tsed\\common\\src\\platform\\services\\PlatformHandler.ts:207:19)"
}
```
throw this error when returning 'DeleteResult', 'InsertResult' and 'UpdateResult'.

**Comment by Romakita** [comment]
@Tarrowren The problem is between TypeORM and the serializer. Can you log the inspect the result returned by: 

```typescript
console.log(await getConnection()
            .createQueryBuilder()
            .delete()
            .from(TTT)
            .where("1 = 1")
            .execute())  // it's probably not the TTT instance but a typeORM wrapper
```
It would be really useful to have reproducible example (in a codesandbox for example) to fix this issue quicky :) 
See you
Romain

**Comment by Tarrowren** [comment]
DeleteResult { affected: 0 }

**Comment by Tarrowren** [comment]
>typeorm/DeleteResult.js
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Result object returned by DeleteQueryBuilder execution.
 */
var DeleteResult = /** @class */ (function () {
    function DeleteResult() {
    }
    return DeleteResult;
}());
exports.DeleteResult = DeleteResult;

//# sourceMappingURL=DeleteResult.js.map
```
>DeleteResult.d.ts
```typescript
/**
 * Result object returned by DeleteQueryBuilder execution.
 */
export declare class DeleteResult {
    /**
     * Raw SQL result returned by executed query.
     */
    raw: any;
    /**
     * Number of affected rows/documents
     * Not all drivers support this
     */
    affected?: number | null;
}
```
I know why now, but I can't fix it myself

**Comment by Tarrowren** [comment]
I've simplified the problem now
```typescript
//I can't modify this object
class Test {
    raw: any;
    affected?: number | null;
}
...

@Controller("/hello-world")
export class HelloWorldController {
    @Get()
    get() {
        const t = new Test();

        t.raw = 1;
        t.affected = 1;

        return t;
    }
}
```
