### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by olegs-hl** [TypedProject/tsed#1154]
Hello, 

I am having a problem with how to init the service or a few services for another service. Here is the explanation of what I have in mind

I have a controller that is calling the service:

```typescript
import { $log, Controller, Get, PathParams, Req } from '@tsed/common';
import { ContentService } from '../../services/contents/ContentService';

@Controller('/content')
export class ContentController {
  constructor(private readonly contentService: ContentService) {}

  @Get('/:url*')
  async getContent(
    @Req(URL) _request: Req,
    @PathParams('url') tenant: string,
  ): Promise<void> {
    const pathUrl: string = _request.url.replace(`/${tenant}`, '');
    const result = await this.contentService.consume(tenant, pathUrl);
    return result;
  }
}
```

here is the partial code for contentService which is calling few other services within.

```typescript
import { Service } from '@tsed/common';
import { Consumer } from '../../lib/Consumer';

@Service()
export class ContentService {
  constructor(private readonly consumer: Consumer) {}

  async consume(tenant: string, contentPath: string) {
.....
   const json = await this.consumer.AwsServiceLoader(tenant, firstComponent, path);
   return json;
}
```

and contentService is calling the configuration Service (the data which provides which DB/API call for each environment (aka dev, stage, prod) and actual library which provide AWS SDI API 

```typescript
import { AwsS3 } from 'api-data-access';
import { Injectable, ProviderScope, Scope } from '@tsed/common';
import apiResponse from '../models/ApiResponse';
import { AppConfig } from '../services/configs/AppConfig';

@Injectable()
@Scope(ProviderScope.SINGLETON)
export class Consumer {

  private folderMap: Map<string, string>;

  constructor(
    private readonly appConfig: AppConfig,
    private readonly awsS3: AwsS3,
  ) {
    this.folderMap = this.setFolderMap();
  }

 ...
}
```

but when trying to compile/start the service, I see the error

```typescript
2020-12-20T18:52:49.463] [DEBUG] [TSED] - Start server...
[2020-12-20T18:52:50.736] [INFO ] [TSED] - Call hook $beforeInit
[2020-12-20T18:52:50.736] [INFO ] [TSED] - Build providers
[2020-12-21T13:39:20.859] [ERROR] [TSED] - UNDEFINED_TOKEN_ERROR: Unable to inject dependency. Given token is undefined. Have you enabled emitDecoratorMetadata in your tsconfig.json or decorated your class with @Injectable, @Service, ... decorator ?

Consumer->constructor(appConfig: undefined, awsS3: AwsS3)
                      ^‾‾‾‾‾‾‾‾
    at Map.mapInvokeOptions (/Users/vault/github/merlin/node_modules/@tsed/di/src/services/InjectorService.ts:615:13)
    at Map.resolve (/Users/vault/github/merlin/node_modules/@tsed/di/src/services/InjectorService.ts:545:74)
    at Map.invoke (/Users/vault/github/merlin/node_modules/@tsed/di/src/services/InjectorService.ts:217:23)
    at /Users/vault/github/merlin/node_modules/@tsed/di/src/services/InjectorService.ts:571:70
    at Array.map (<anonymous>)
```

AppConfig is defined and has a constructor as well as my tsconfig.json has `emitDecoratorMetadata` true

```typescript
import { Injectable, ProviderScope, Scope } from '@tsed/common';
import * as jsontxt from './appConfig.json';

@Injectable()
@Scope(ProviderScope.SINGLETON)
export class AppConfig {
  private NODE_ENV: string;
  private configObj: any;

  constructor() {
    this.NODE_ENV = process.env.ENV || 'dev';
    this.configObj = jsontxt;
  }

  public config() {
    return this.configObj[this.NODE_ENV];
  }
}
```

Any idea what am I doing so much wrong?
Thank you in advance for your help,

**Comment by Romakita** [comment]
Hello @olegs-hl,

In most case, if the problem isn't a tsconfig issue, it means you have a circular dependencies (or bad export) between two or more files. 
Two confirm this problem, you can add a console.log just before the class:

```typescript
import { AwsS3 } from 'api-data-access';
import { Injectable, ProviderScope, Scope } from '@tsed/common';
import apiResponse from '../models/ApiResponse';
import { AppConfig } from '../services/configs/AppConfig';

console.log('==>AppConfig', AppConfig) // if it's undefined, it means you have circular dependencies issue

@Injectable()
@Scope(ProviderScope.SINGLETON)
export class Consumer {

  private folderMap: Map<string, string>;

  constructor(
    private readonly appConfig: AppConfig,
    private readonly awsS3: AwsS3,
  ) {
    this.folderMap = this.setFolderMap();
  }

 ...
}
```
Can you try it please :) 
Romain
