### ISSUE TITLE
Cannot find module './DecoratorUtils'

### ISSUE THREAD

**Issue by avalladaresm** [TypedProject/tsed#1228]
## Information

- **Version:** 6.23.4
- Packages: 

I am deploying a ts.ed app to Azure App Service, everything goes smooth until I try to load my website, to which I get an error on the App Service Editor, that says:

```
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module './DecoratorUtils'
Require stack:
- D:\home\site\wwwroot\node_modules\@tsed\core\lib\utils\index.js
- D:\home\site\wwwroot\node_modules\@tsed\core\lib\index.js
- D:\home\site\wwwroot\node_modules\@tsed\common\lib\index.js
- D:\home\site\wwwroot\dist\index.js
- D:\Program Files (x86)\iisnode\interceptor.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\@tsed\core\lib\utils\index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```
Any idea what could cause the issue?

My `package.json` looks like this:
```
{
  "name": "myapp",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "yarn tsc",
    "tsc": "tsc --project tsconfig.compile.json",
    "tsc:w": "tsc --project tsconfig.json -w",
    "start": "nodemon --watch \"src/**/*.ts\" --ignore \"node_modules/**/*\" --exec ts-node src/index.ts",
    "start:prod": "cross-env NODE_ENV=production node dist/index.js",
    "typeorm": "tsed typeorm"
  },
  "dependencies": {
    "@sendgrid/mail": "^7.4.2",
    "@tsed/ajv": "^6.23.4",
    "@tsed/common": "^6.23.4",
    "@tsed/core": "^6.23.4",
    "@tsed/di": "^6.23.4",
    "@tsed/exceptions": "^6.23.4",
    "@tsed/json-mapper": "^6.23.4",
    "@tsed/openspec": "^6.23.4",
    "@tsed/platform-express": "^6.23.4",
    "@tsed/schema": "^6.23.4",
    "@tsed/swagger": "^6.23.4",
    "@tsed/typeorm": "^6.23.4",
    "ajv": "^7.0.3",
    "bcrypt": "^5.0.0",
    "body-parser": "^1.19.0",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "date-fns": "^2.16.1",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "jsonwebtoken": "^8.5.1",
    "method-override": "^3.0.0",
    "mssql": "^6.3.1",
    "typeorm": "^0.2.30"
  },
  "devDependencies": {
    "@tsed/cli-plugin-typeorm": "2.9.0",
    "@types/compression": "^1.7.0",
    "@types/cookie-parser": "^1.4.2",
    "@types/cors": "^2.8.9",
    "@types/express": "^4.17.11",
    "@types/method-override": "0.0.31",
    "@types/multer": "^1.4.5",
    "@types/node": "^14.14.22",
    "concurrently": "^5.3.0",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.3"
  },
  "readme": "ERROR: No README data found!",
  "_id": "myapp@1.0.0"
}
```

Any help would be very much appreciated!

**Comment by Romakita** [comment]
Hello @avalladaresm 
Can you fix the package please, then run npm install & npm dedup (or yarn): 

```
 "@tsed/ajv": "6.23.4",
    "@tsed/common": "6.23.4",
    "@tsed/core": "6.23.4",
    "@tsed/di": "6.23.4",
    "@tsed/exceptions": "6.23.4",
    "@tsed/json-mapper": "6.23.4",
    "@tsed/openspec": "6.23.4",
    "@tsed/platform-express": "6.23.4",
    "@tsed/schema": "6.23.4",
    "@tsed/swagger": "6.23.4",
    "@tsed/typeorm": "6.23.4",
```

See you
Romain

**Comment by avalladaresm** [comment]
Hey @Romakita,
So, I did the following: First, I was deploying the web app service in a Windows Server machine, and that's where I had the issue I mentioned above. Then I decided to deploy it again, but this time, in a Linux machine and I was no longer getting that error, even without applying the changes that you mentioned, so I got it working at the end, it was my first time deploying something as such (staging in this case), I hope I did it correctly though, haha.

Anyway, I will still fix the package as you mentioned, I believe that is the better option. Also, is there a way to protect the API, say, with a simple login? The current behavior is that as soon as I load the website, all of my endpoints show up. I already have bearer authorization working but it would be nice to protect the endpoints from showing up initially as well.

**Comment by Romakita** [comment]
Hello @avalladaresm 
You have the @tsed/passport for that or @tsed/oidc-provider (OAuth/ OpenID).
Passport: https://tsed.io/tutorials/passport.htm
OIDC:  https://tsed.io/tutorials/oidc.html

Read the documentation and tell if you have any question ;)

Note: for your issue on windows server, sometimes, Windows doesn't download correctly all files :( Isn't just related to Ts.ED.

See you
Romain
