### ISSUE TITLE
[BUG] Server crashes with @tsed/seq

### ISSUE THREAD

**Issue by Elyspio** [TypedProject/tsed#1306]
Information
Version: 6.35.1
Packages: @Tsed/Seq

Hello, I would like to use the tsed/seq package but once I'm importing it, the server crashs

Code

```
...
import "@tsed/seq"; // import seq Ts.ED module


export const webConfig: Partial<TsED.Configuration> = {
    rootDir,
    seq: {
        url: "http://192.168.0.60:1234"
    },
   ...
}
```

Error log
```log
[2021-03-24T19:55:40.517] [ERROR] [Automatize -- Manager] - TypeError: Cannot read property 'Logger' of undefined
    at SeqAppender.build (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\logger-seq\src\SeqAppender.ts:20:29)
    at new BaseAppender (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\logger\src\appenders\class\BaseAppender.ts:68:20)
    at new SeqAppender (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\logger-seq\src\SeqAppender.ts:15:1)
    at LoggerAppenders.set (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\logger\src\logger\class\LoggerAppenders.ts:52:36)
    at SeqModule.$afterRoutesInit (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\seq\src\SeqModule.ts:18:38)
    at Map.emit (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\di\src\class\LocalsContainer.ts:15:34)
    at PlatformExpress.callHook (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:227:22)
    at PlatformExpress.loadRoutes (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:354:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PlatformExpress.loadRoutes (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\platform-express\src\components\PlatformExpress.ts:83:5)
    at PlatformExpress.runLifecycle (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:170:5)
    at PlatformExpress.bootstrap (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:315:5)
    at bootstrap (P:\own\desktop\cross-platform\automatize-github-docker\manager\back\src\app.ts:18:26)
```

Acceptance criteria
 The app must not crash :) 

Sincerly

**Comment by Romakita** [comment]
Hello @Elyspio 
Have you upgraded all Ts.ED packages and have the same version for all Ts.ED package :) ?

**Comment by Elyspio** [comment]
Yes, as you can see bellow they are all on the 6.35.1 version 
```
"@tsed/common": "^6.35.1",
"@tsed/core": "^6.35.1",
"@tsed/di": "^6.35.1",
"@tsed/socketio": "^6.35.1",
"@tsed/platform-express": "^6.35.1",
"@tsed/schema": "^6.35.1",
"@tsed/swagger": "^6.35.1",
"@tsed/seq": "6.35.1",
```

**Comment by Romakita** [comment]
Ok probably the issue. I'll publish a release now!

**Comment by Romakita** [comment]
Release is in progress
