### ISSUE TITLE
[BUG] Error on creating Socket namespace

### ISSUE THREAD

**Issue by VLRTroll** [TypedProject/tsed#1333]
Hi, guys!

I'm trying to just connect the `@tsed/socketio` into my project, but when I try follow the [documentation](https://tsed.io/tutorials/socket-io.html#socket-service) to use socket my namespace, as a service, inside a controller it's throwing the following error.

```bash
[2021-04-05T18:26:19.605] [INFO ] [TSED] - Call hook $beforeListen
[2021-04-05T18:26:19.618] [INFO ] [TSED] - Listen server on http://0.0.0.0:8083
[2021-04-05T18:26:19.619] [INFO ] [TSED] - Call hook $afterListen
[2021-04-05T18:26:19.622] [ERROR] [TSED] - TypeError: Cannot read property 'set' of undefined
    at NotificationService.set (C:\project\node_modules\@tsed\core\src\domain\Store.ts:110:15)
    at SocketHandlersBuilder.build (C:\project\node_modules\@tsed\socketio\src\class\SocketHandlersBuilder.ts:47:20)
    at SocketIOService.addSocketProvider (C:\project\node_modules\@tsed\socketio\src\services\SocketIOService.ts:61:95)
    at C:\project\node_modules\@tsed\socketio\src\SocketIOModule.ts:46:76
    at Array.forEach (<anonymous>)
    at SocketIOModule.$afterListen (C:\project\node_modules\@tsed\socketio\src\SocketIOModule.ts:46:33)
    at Map.emit (C:\project\node_modules\@tsed\di\src\class\LocalsContainer.ts:15:34)
    at PlatformExpress.callHook (C:\project\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:227:22)
    at PlatformExpress.listen (C:\project\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:192:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at bootstrap (C:\project\src\/index.ts:11:5)
```

<b> Does Somebody know how can I fix this? </b>

## Information

- **Version:** 6.36.0

<details>
  <summary>package.json file</summary>
  
```jsonc
{
 ...
"dependencies": {
    "@tsed/ajv": "^6.36.0",
    "@tsed/cli": "^2.12.0",
    "@tsed/common": "^6.36.0",
    "@tsed/core": "^6.36.0",
    "@tsed/di": "^6.36.0",
    "@tsed/exceptions": "^6.36.0",
    "@tsed/json-mapper": "^6.36.0",
    "@tsed/passport": "^6.36.0",
    "@tsed/platform-express": "^6.36.0",
    "@tsed/schema": "^6.36.0",
    "@tsed/socketio": "^6.36.0",
    "@tsed/swagger": "^6.36.0",
    "@tsed/typeorm": "^6.36.0",
    "ajv": "^7.2.4",
    "bcrypt": "^5.0.1",
    "body-parser": "^1.19.0",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "express": "^4.17.1",
    "http": "^0.0.1-security",
    "jsonwebtoken": "^8.5.1",
    "method-override": "^3.0.0",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "socket.io": "^4.0.1",
    "sqlite3": "^5.0.2",
    "typeorm": "^0.2.31"
  },
  "devDependencies": {
    "@tsed/cli-plugin-eslint": "2.12.0",
    "@tsed/cli-plugin-jest": "2.12.0",
    "@tsed/cli-plugin-passport": "2.12.0",
    "@tsed/cli-plugin-typeorm": "2.12.0",
    "@types/bcrypt": "^3.0.0",
    "@types/compression": "^1.7.0",
    "@types/cookie-parser": "^1.4.2",
    "@types/cors": "^2.8.10",
    "@types/express": "^4.17.11",
    "@types/jest": "^26.0.22",
    "@types/method-override": "^0.0.31",
    "@types/multer": "^1.4.5",
    "@types/node": "^14.14.36",
    "@types/passport": "^1.0.6",
    "@types/passport-jwt": "^3.0.5",
    "@types/passport-local": "^1.0.33",
    "@types/socket.io": "^2.1.13",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "babel-plugin-transform-typescript-metadata": "^0.3.2",
    "concurrently": "^6.0.0",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.2.3"
  },
  "tsed": {
    "packageManager": "yarn",
    "convention": "default"
  }
}
```
</details>

## Code

<details>
  <summary>Server.ts</summary>
  
```ts
import '@tsed/ajv';
import { $log, PlatformApplication } from '@tsed/common';
import { Env } from '@tsed/core';
import { Configuration, Inject } from '@tsed/di';

import '@tsed/passport';
import '@tsed/platform-express'; // /!\ keep this import
import '@tsed/socketio';
import '@tsed/swagger';
import '@tsed/typeorm';
import bodyParser from 'body-parser';
import compress from 'compression';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import methodOverride from 'method-override';

import typeormConfig from '../ormconfig.json';

import { IndexController } from './controllers/pages/IndexController';

export const rootDir = __dirname;
export const isProduction = process.env.NODE_ENV === Env.PROD;

if (isProduction) {
  $log.appenders.set('stdout', {
    type: 'stdout',
    levels: ['info', 'debug'],
    layout: {
      type: 'json',
    },
  });

  $log.appenders.set('stderr', {
    levels: ['trace', 'fatal', 'error', 'warn'],
    type: 'stderr',
    layout: {
      type: 'json',
    },
  });
}

@Configuration({
  rootDir,
  acceptMimes: ['application/json'],
  httpPort: process.env.PORT || 8083,
  httpsPort: false, // CHANGE
  logger: {
    disableRoutesSummary: isProduction,
  },
  mount: {
    '/rest': [`${rootDir}/controllers/**/*.ts`],
    '/': [IndexController],
  },
  componentsScan: [
    `${rootDir}/protocols/*.ts`, // scan protocols directory
  ],
  passport: {},
  swagger: [
    {
      path: '/v2/docs',
      specVersion: '2.0',
    },
    {
      path: '/v3/docs',
      specVersion: '3.0.1',
    },
  ],
  views: {
    root: `${rootDir}/../views`,
    viewEngine: 'ejs',
  },
  typeorm: [typeormConfig as any],
  exclude: ['**/*.spec.ts'],
})
export class Server {
  @Inject()
  app: PlatformApplication;

  @Configuration()
  settings: Configuration;

  $beforeRoutesInit(): void {
    this.app
      .use(cors())
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(
        bodyParser.urlencoded({
          extended: true,
        }),
      );
  }
}
```
</details>

<details>
  <summary>NotificationService.ts</summary>
  
```ts
import { Nsp, SocketService } from '@tsed/socketio';

@SocketService('/my-namespace')
export class NotificationService {
  @Nsp nsp: Nsp;

  helloAll() {
    this.nsp.emit('hi', 'everyone!');
  }
}

```
</details>

<details>
  <summary>NotificarionController.ts</summary>
  
```ts
import { Controller, Get } from '@tsed/common';

import { NotificationService } from '../services/sockets/NotificationService';

@Controller('/')
export class NotificationController {
  constructor(private notificationService: NotificationService) {

  }

  @Get('/allo')
  allo() {
    this.notificationService.helloAll();

    return 'is sent';
  }
}

```
</details>

**Comment by VLRTroll** [comment]
I really appreciate your effort with this bug. But, now it's returning the following error, @Romakita:
```
[2021-04-14T09:59:26.172] [INFO ] [TSED] - Socket events mounted:
[2021-04-14T09:59:26.173] [ERROR] [TSED] - TypeError: Cannot read property 'length' of undefined
    at C:\project\node_modules\@tsed\common\node_modules\@tsed\logger\src\logger\utils\tableUtils.ts:85:81
    at Array.forEach (<anonymous>)
    at buildLineData (C:\project\node_modules\@tsed\common\node_modules\@tsed\logger\src\logger\utils\tableUtils.ts:82:23)
    at C:\project\node_modules\@tsed\common\node_modules\@tsed\logger\src\logger\utils\tableUtils.ts:125:15
    at Array.forEach (<anonymous>)
    at Object.drawTable (C:\project\node_modules\@tsed\common\node_modules\@tsed\logger\src\logger\utils\tableUtils.ts:123:8)
    at Logger.drawTable (C:\project\node_modules\@tsed\common\node_modules\@tsed\logger\src\logger\class\Logger.ts:168:12)
    at SocketIOModule.printSocketEvents (C:\project\node_modules\@tsed\socketio\src\SocketIOModule.ts:88:22)
    at SocketIOModule.$afterListen (C:\project\node_modules\@tsed\socketio\src\SocketIOModule.ts:49:12)
    at Map.emit (C:\project\node_modules\@tsed\di\src\class\LocalsContainer.ts:15:34)
    at PlatformExpress.callHook (C:\project\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:227:22)
    at PlatformExpress.listen (C:\project\node_modules\@tsed\common\src\platform\builder\PlatformBuilder.ts:192:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at bootstrap (C:\project\src\/index.ts:11:5)
```
I guess it's something related with the display of socket namespaces table. (I'm on version 6.41.1)

**Comment by Romakita** [comment]
Have you updated all Ts.ED packages ?

**Comment by Romakita** [comment]
Here is the code about the display table.

```typescript
  protected printSocketEvents() {
    const list = this.getWebsocketServices().reduce((acc: any[], provider) => {
      const {handlers = {}, namespace} = provider.store.get<SocketProviderMetadata>("socketIO");

      if (namespace) {
        Object.keys(handlers)
          .filter((key) => ["$onConnection", "$onDisconnect"].indexOf(key) === -1)
          .forEach((key) => {
            const handler = handlers[key];
            acc.push({
              namespace,
              inputEvent: handler.eventName,
              outputEvent: (handler.returns && handler.returns.eventName) || "",
              outputType: (handler.returns && handler.returns.type) || "",
              name: `${nameOf(provider.useClass)}.${handler.methodClassName}`
            });
          });
      }

      return acc;
    }, []);

    this.injector.logger.info("Socket events mounted:");

    const str = $log.drawTable(list, {
      padding: 1,
      header: {
        namespace: "Namespace",
        inputEvent: "Input event",
        outputEvent: "Output event",
        outputType: "Output type",
        name: "Class method"
      }
    });

    this.injector.logger.info("\n" + str.trim());

    this.injector.logger.info("Socket server started...");
  }
```

For me, isn't possible to have an empty array, the reduce function return always an array...

**Comment by VLRTroll** [comment]
Hi, @Romakita! Yes, I updated all the TsED modules to the latest version (6.43.3)

Inspecting the error stack, I found the specific instruction that is throwing the error. The `$log.drawTable` calls the following method:

```ts
export function buildLineData(scope: any, fields: any, settings: ITableSettings) {
  let line = "";

  Object.keys(fields).forEach(key => {
    line += "│ ";
    line += scope[key];
    line += charRepeater(fields[key] + 2 * (settings.padding! - 1) - scope[key].length, " "); // throws the error
    line += " ";
  });

  line += "│";
  return line;
}
```

So I guess some property is been setted incorretly by the `reduce`.

But trying other ways, I found something that works a bit better:


<details>
  <summary>NotificarionService.ts</summary>

```ts
import { Nsp, SocketService } from '@tsed/socketio';

@SocketService()
export class NotificationService {
  @Nsp('/') nsp: Nsp;

  helloAll() {
    this.nsp.emit('hi', 'everyone!');
  }
}
```
</details>

I needed to specify the namespace in the `@Nps` decorator to work. But the server socket namespaces are still not listing on the terminal table. And when I try to connect a client the following error is thrown:

```
C:\project\node_modules\@tsed\socketio\lib\class\SocketHandlersBuilder.js:121
        Object.keys(this.socketProviderMetadata.handlers)
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SocketHandlersBuilder.buildHandlers (C:\project\node_modules\@tsed\socketio\src\class\SocketHandlersBuilder.ts:145:12)
    at SocketHandlersBuilder.onConnection (C:\project\node_modules\@tsed\socketio\src\class\SocketHandlersBuilder.ts:89:10)
    at C:\project\node_modules\@tsed\socketio\src\services\SocketIOService.ts:33:19
    at Array.forEach (<anonymous>)
    at Namespace.<anonymous> (C:\project\node_modules\@tsed\socketio\src\services\SocketIOService.ts:32:24)
    at Namespace.emit (events.js:315:20)
    at Namespace.EventEmitter.emit (domain.js:467:12)
    at Namespace.emitReserved (C:\project\node_modules\socket.io\dist\typed-events.js:56:22)     
    at C:\project\node_modules\socket.io\dist\namespace.js:139:26
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[nodemon] app crashed - waiting for file changes before starting...
```

Do you have some example working on your machine to test here?
