### ISSUE TITLE
Adding validation decorators to bodyParams throw typeError

### ISSUE THREAD

**Issue by yantrab** [TypedProject/tsed#429]
## Informations

Type | Version
---|---
Bug | 4.x

****

## Description
Adding validation decorators to bodyParams throw typeError:
```
 async login(@Required() @Email()  @BodyParams("email") email: string,
                @Required() @MinLength(6) @BodyParams("password") password: string,
                @Req() request: Express.Request,
                @Res() response: Express.Response) {
}
```
[2018-08-06T14:36:53.912] [ERROR] [TSED] - TypeError: Cannot read property 'mapper' of undefined
    at MinLength.decoratorSchemaFactory_1.decoratorSchemaFactory.schema (c:\Users\arkadiy\Desktop\p-proj\web-server\node_modules\@tsed\src\common\jsonschema\decorators\minLength.ts:78:12)
    at parameters (c:\Users\arkadiy\Desktop\p-proj\web-server\node_modules\@tsed\src\common\jsonschema\utils\decoratorSchemaFactory.ts:24:25)
    at c:\Users\arkadiy\Desktop\p-proj\web-server\controllers\auth.controller.ts:12:37
    at DecorateProperty (c:\Users\arkadiy\Desktop\p-proj\web-server\node_modules\reflect-metadata\Reflect.ts:1214:35)
    at Object.decorate (c:\Users\arkadiy\Desktop\p-proj\web-server\node_modules\reflect-metadata\Reflect.ts:737:24)
    at __decorate (c:\Users\arkadiy\Desktop\p-proj\web-server\controllers\auth.controller.ts:4:92)
    at Object.<anonymous> (c:\Users\arkadiy\Desktop\p-proj\web-server\controllers\auth.controller.ts:65:1)
    at Module._compile (module.js:635:30)
    at Module.m._compile (c:\Users\arkadiy\Desktop\p-proj\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:646:10) 

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hi @yantrab 

MinLength and other decorators to validate a schema cannot be used on parameters. If you want validate your data, you have to create Model.

According to your example:

```typescript
class UserLogin {
    @Email()
    @Required()
    email: string;
   
    @Required()
    @MinLength(6)
    password: string;
}

async login(@BodyParams() login: UserLogin, @Req() request: Express.Request,
                    @Res() response: Express.Response) {

}
```

See you :)
