### ISSUE TITLE
AJV Incorrect validation on string array

### ISSUE THREAD

**Issue by waqas19921** [TypedProject/tsed#578]
## Information

- **Version:** 5.20.1
- **Type:** Issue

## Description
AJV

## Example
I have a user schema where i want to send array of phone numbers to store in another table called PhoneNumber. I am unable to validate it using `string[]`
Here is the property definition
```typescript
  @Description('A user has multiple phone numbers')
  @OneToMany(() => PhoneNumber, phoneNo => phoneNo.user, { nullable: true })
  phoneNumbers: PhoneNumber[] | string[];
```
I have applied validation using below code
```typescript
async create(
    @Required() @BodyParams() user: BaseUser,
  ) 
```

i am getting following error message
```
{ AJV_VALIDATION_ERROR: At BaseUser.phoneNumbers[0], value '090078602123' should be object
          at AjvService.buildErrors (E:\projects\node_modules\@tsed\ajv\src\services\AjvService.ts:83:12)
          at test (E:\projects\node_modules\@tsed\ajv\src\services\AjvService.ts:54:22)
          at Object.keys.forEach (E:\projects\node_modules\@tsed\ajv\src\services\AjvService.ts:59:9)
          at Array.forEach (<anonymous>)
          at AjvService.validate (E:\projects\lean\lean-be\node_modules\@tsed\ajv\src\services\AjvService.ts:58:31)
          at FilterBuilder.pipe (E:\projects\node_modules\@tsed\common\src\filters\class\FilterBuilder.ts:140:29)
```

**Comment by Romakita** [comment]
Hello @waqas19921 

You have to use additional decorators to tell AJV how you property should be validated. Typescript doesn't store metadata correctly when you use twice or more types.
And in your case, it's big tricky because you use a class symbol or string type.

The fix could something like that:
```typescript
  @Description('A user has multiple phone numbers')
  @Schema({
      type: "object",
      items: {
        anyOf: [
          {type: string},
          {$ref: '#/definitions/PhoneNumber'}
        ]
      }
   })
  @OneToMany(() => PhoneNumber, phoneNo => phoneNo.user, { nullable: true })
  phoneNumbers: PhoneNumber[] | string[];
```

Tell me if it works :) (maybe I can reuse this code and implement a custom decorator).
Romain

**Comment by IARKI** [comment]
@AllowTypes("string")
worked for me
