### ISSUE TITLE
Always report "undefined" in $onServerInitError hook

### ISSUE THREAD

**Issue by codyrin93** [TypedProject/tsed#652]
## Information

- **Version:** 5.31.3
- **Type:** Issue/Story

## Description
$onServerInitError hook always shown "undefined" when the server failed to initialize. This would be hard to debug.

I find this when I use a self-referencing model with```@BodyParams()``` in controller. The error stack shows that it fail to build schema. Is there any workaround on it?

## Example (Produce error by ```$onInit()``` hook)
```typescript
class TsedServer extends ServerLoader {
    public async $onInit(): Promise<void> {
        throw new Error("Foo Bar");
    }

    public $onServerInitError(err: Error): void {
        $log.fatal(err);
        process.exit(1);
    }
}
```

In version 5.27.4, the logger will show:
```
[2019-09-25T11:37:34.027] [FATAL] [TSED] - Error: Foo Bar
```

In version 5.31.3, the logger will show:
```
[2019-09-25T11:40:05.007] [FATAL] [TSED] - Error: undefined
```

## Example (Produce error by self/circular reference in model class)

```typescript
export class CircularModel {
    @PropertyType(CircularModel)
    public circularModels?: CircularModel[];
}

@Controller("/dummy")
export class DummyController {
    @Post("/circular")
    public circularTest(@BodyParams()c: CircularModel): CircularModel {
        return c;
    }
}
```

In version 5.27.4, when the server start, the logger will show:

```
[2019-09-25T11:59:30.071] [FATAL] [TSED] - RangeError: Maximum call stack size exceeded
    at Array.forEach (<anonymous>)
    at JSON_SCHEMA_FIELDS.forEach (\node_modules\@tsed\common\src\jsonschema\registries\JsonSchemesRegistry.ts:132:28)
    at Array.forEach (<anonymous>)
    at Map.findReferences (\node_modules\@tsed\common\src\jsonschema\registries\JsonSchemesRegistry.ts:125:24)
    at Map.getSchema (\node_modules\@tsed\common\src\jsonschema\registries\JsonSchemesRegistry.ts:110:10)
    at core_1.ancestorsOf.reduce (\node_modules\@tsed\common\src\jsonschema\registries\JsonSchemesRegistry.ts:89:29)
    at Array.reduce (<anonymous>)
    at Map.getSchemaDefinition (\node_modules\@tsed\common\src\jsonschema\registries\JsonSchemesRegistry.ts:88:32)
    at OpenApiModelSchemaBuilder.getClassSchema (\node_modules\@tsed\swagger\src\class\OpenApiModelSchemaBuilder.ts:117:40)
    at OpenApiModelSchemaBuilder.build (\node_modules\@tsed\swagger\src\class\OpenApiModelSchemaBuilder.ts:25:33)
```

In version 5.31.3, the logger will show:
```
[2019-09-25T13:00:59.023] [FATAL] [TSED] - undefined
```

## Acceptance criteria

- [ ] $onServerInitError hook should allow to show error stack
- [ ] should able to generate schema with circular referencing model

**Comment by Romakita** [comment]
Hello @ringolin93 

The way to handle error has changed since a long time. When you bootstrap your server with 5.27 and under you have to write this:

```typescript
new Server().start().catch(er => $log.error(er))
```
With 5.27+, it's possible to handle error as following:
```
async bootstrap(){
   try {   
      const server = await ServerLoader.bootstrap(Server)
      await server.listen()
   }catch(er){
     $log.error(er)
   }
}
```
> Note: $onServerInitError will be removed in v6 :)

For the circularModel, is not supported. TypeScript doesn't generate correctly the metadata and store by default Object type.  This issue has the same problematic #642 

The only way is to create a new decorator to do that.

**Comment by Romakita** [comment]
v6 support this feature :)
