### ISSUE TITLE
[QUESTION] Getting TypeORM connection in $afterRoutesInit - ServerLoader

### ISSUE THREAD

**Issue by RickStanley** [TypedProject/tsed#771]
Hello, I'm trying to get an TypeORM instance (the only connection that I have set up as "default") in `$afterRoutesInit` called from `Server` class, but `typeORMService` comes empty.
My question is if it is a valid call and/or configuration, because I don't want to create another file for just a DB Service.

```typescript
export class Server extends ServerLoader implements AfterRoutesInit {

  constructor(private typeORMService: TypeORMService) {
  }

 ...

  public $afterRoutesInit(): void | Promise<any> {
    console.log(this.typeORMService); // {}
  }
}
```

I'm doing this because I want to initialize my DB with some basic initial seed. I know that TypeORM sugests [creating a migration](https://github.com/typeorm/typeorm/issues/1550#issuecomment-362999036), but I just want to keep it simple, less configurations if possible.

**Comment by Romakita** [comment]
If you add .get() to this.typeORMService. Do you have something ?

```
export class Server extends ServerLoader implements AfterRoutesInit {

  constructor(private typeORMService: TypeORMService) {
  }

 ...

  public $afterRoutesInit(): void | Promise<any> {
    console.log(this.typeORMService.get()); // ---- ?
  }
}

**Comment by RickStanley** [comment]
I'm sorry, I forgot to include this part, here it's in debug mode:

```bash
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src\**\*.ts
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
[2020-02-26T13:40:52.893] [DEBUG] [TSED] - Scan components
[2020-02-26T13:40:53.978] [INFO ] [TSED] - Call hook $beforeInit
[2020-02-26T13:40:53.980] [INFO ] [TSED] - Call hook $onInit
[2020-02-26T13:40:53.981] [INFO ] [TSED] - Build providers
[2020-02-26T13:40:53.984] [DEBUG] [TSED] - settings.scopes => { controller: 'singleton' }
[2020-02-26T13:40:53.987] [DEBUG] [TSED] - settings.rootDir => D:\DEV\blogueiros-api-tsed\src
[2020-02-26T13:40:53.987] [DEBUG] [TSED] - settings.env => development
[2020-02-26T13:40:53.988] [DEBUG] [TSED] - settings.httpPort => 8080
[2020-02-26T13:40:53.989] [DEBUG] [TSED] - settings.httpsPort => false
[2020-02-26T13:40:53.990] [DEBUG] [TSED] - settings.version => 1.0.0
[2020-02-26T13:40:53.990] [DEBUG] [TSED] - settings.uploadDir => ${rootDir}/uploads
[2020-02-26T13:40:53.991] [DEBUG] [TSED] - settings.logger => { debug: true, level: 'debug', logRequest: true, jsonIndentation: 2 }
[2020-02-26T13:40:53.991] [DEBUG] [TSED] - settings.errors => { headerName: 'errors' }
[2020-02-26T13:40:53.992] [DEBUG] [TSED] - settings.mount => {
  '/v1': [ 'D:\\DEV\\blogueiros-api-tsed\\src/controllers/**/**Ctrl.ts' ]
}
[2020-02-26T13:40:53.993] [DEBUG] [TSED] - settings.exclude => [ '**/*.spec.ts', '**/*.spec.js' ]
[2020-02-26T13:40:53.994] [DEBUG] [TSED] - settings.componentsScan => [
  'D:\\DEV\\blogueiros-api-tsed\\src/services/*.ts',
  'D:\\DEV\\blogueiros-api-tsed\\src/repositories/*.ts',
  'D:\\DEV\\blogueiros-api-tsed\\src/protocols/*.ts'
]
[2020-02-26T13:40:53.995] [DEBUG] [TSED] - settings.acceptMimes => [ 'application/json' ]
[2020-02-26T13:40:53.995] [DEBUG] [TSED] - settings.debug => true
[2020-02-26T13:40:53.996] [DEBUG] [TSED] - settings.typeorm => [
  {
    name: 'default',
    type: 'mariadb',
    host: 'localhost',
    username: 'root',
    password: '123',
    database: 'blogueiros',
    port: 3306,
    charset: 'UTF8MB4_GENERAL_CI',
    entities: [ 'D:\\DEV\\blogueiros-api-tsed\\src/entities/*.ts' ],
    migrations: [ 'D:\\DEV\\blogueiros-api-tsed\\src/migrations/*.ts' ],
    subscribers: [ 'D:\\DEV\\blogueiros-api-tsed\\src/subscribers/*.ts' ],
    synchronize: true
  }
]
[2020-02-26T13:40:54.000] [DEBUG] [TSED] - settings.swagger => [ { path: '/v1/docs', doc: 'api-v1' } ]
[2020-02-26T13:40:54.009] [INFO ] [TSED] - Create connection with typeorm to database: default
[2020-02-26T13:40:54.010] [DEBUG] [TSED] - options: {"name":"default","type":"mariadb","host":"localhost","username":"root","password":"123","database":"blogueiros","port":3306,"charset":"UTF8MB4_GENERAL_CI","entities":["D:\\DEV\\blogueiros-api-tsed\\src/entities/*.ts"],"migrations":["D:\\DEV\\blogueiros-api-tsed\\src/migrations/*.ts"],"subscribers":["D:\\DEV\\blogueiros-api-tsed\\src/subscribers/*.ts"],"synchronize":true}
[2020-02-26T13:40:58.144] [INFO ] [TSED] - Connected with typeorm to database: default
[2020-02-26T13:40:58.147] [DEBUG] [TSED] - Settings and injector loaded
[2020-02-26T13:40:58.148] [INFO ] [TSED] - Call hook $afterInit
[2020-02-26T13:40:58.149] [DEBUG] [TSED] - Mount middlewares
[2020-02-26T13:40:58.150] [INFO ] [TSED] - Call hook $onMountingMiddlewares
[2020-02-26T13:40:58.151] [INFO ] [TSED] - Call hook $beforeRoutesInit
[2020-02-26T13:40:58.155] [INFO ] [TSED] - Load routes
[2020-02-26T13:40:58.156] [INFO ] [TSED] - Call hook $onRoutesInit
[2020-02-26T13:40:58.160] [INFO ] [TSED] - Call hook $afterRoutesInit
[2020-02-26T13:40:58.162] [ERROR] [TSED] - TypeError: this.typeORMService.get is not a function
    at Server.$afterRoutesInit (D:\DEV\blogueiros-api-tsed\src\Server.ts:88:37)
    at Object.<anonymous> (D:\DEV\blogueiros-api-tsed\node_modules\@tsed\common\src\server\utils\callHook.ts:25:26)
    at Generator.next (<anonymous>)
    at D:\DEV\blogueiros-api-tsed\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\DEV\blogueiros-api-tsed\node_modules\tslib\tslib.js:106:16)
    at Object.callHook (D:\DEV\blogueiros-api-tsed\node_modules\@tsed\common\lib\server\utils\callHook.js:7:20)
    at Server.callHook (D:\DEV\blogueiros-api-tsed\node_modules\@tsed\common\src\server\components\ServerLoader.ts:390:12)
    at Server.<anonymous> (D:\DEV\blogueiros-api-tsed\node_modules\@tsed\common\src\server\components\ServerLoader.ts:434:16)
    at Generator.next (<anonymous>)
```

with:
```typescript
export class Server extends ServerLoader implements AfterRoutesInit {

  constructor(private typeORMService: TypeORMService) {
    super();
  }

  public $beforeRoutesInit(): void | Promise<any> {
    this
      .use(GlobalAcceptMimesMiddleware)
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({
        extended: true
      }));
  }

  public $afterRoutesInit(): void | Promise<any> {
    console.log(this.typeORMService.get());
    
  }
}
```

**Comment by Romakita** [comment]
OK I forgot you have injected the service in server loader. Injection isn't available on server constructor. You have to use server.injector.get() to retrieve the TypeORMService.

Here the right code:

```typescript
export class Server extends ServerLoader implements AfterRoutesInit {
  public $beforeRoutesInit(): void | Promise<any> {
    this
      .use(GlobalAcceptMimesMiddleware)
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({
        extended: true
      }));
  }

  public $afterRoutesInit(): void | Promise<any> {
     const typeORMService = this.injector.get<TypeORMService>(TypeORMService);
    console.log(typeORMService.get());
  }
}
```
Try this :)
See you

**Comment by RickStanley** [comment]
Thanks, works like a charm!
