### ISSUE TITLE
[ConverterService] Property 0 on class String is not allowed 

### ISSUE THREAD

**Issue by chiqui3d** [TypedProject/tsed#788]
Suddenly it stopped working and showed this error. I don't know if I updated. But I'm in the latest version 5.44.13 

Full error:

```
{
"message":"Property 0 on class String is not allowed.",
"success":false,
"status":400,
"statusCode":400,
"stack":"BAD_REQUEST: Property 0 on class String is not allowed.\n at ConverterService.checkStrictModelValidation (G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:288:13)\n at ConverterService.convertProperty (G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:229:10)\n at G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:190:21\n at Array.forEach (<anonymous>)\n at ConverterService.deserialize (G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:187:24)\n at DeserializerPipe.transform (G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\mvc\\pipes\\DeserializerPipe.ts:10:34)\n at G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\platform\\services\\PlatformHandler.ts:214:75\n at Array.reduce (<anonymous>)\n at PlatformHandler.mapParam (G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\platform\\services\\PlatformHandler.ts:214:24)\n at G:\\www\\api-profit-new\\app\\api\\node_modules\\@tsed\\common\\src\\platform\\services\\PlatformHandler.ts:187:51",
"origin":"",
"path":"/auth/login",
"timestamp":"2020-03-27T22:54:04.481Z"
}
```

**Comment by chiqui3d** [comment]
If I set the `validationModelStrict ` option to `false`, then it works, but the data at the frontEnd is already different.

**Comment by Romakita** [comment]
Hello @chiqui3d 
I've enough details to help you. What is the model used and which payload request is sent to the server?
There is no change on ConverterService itself since a long time so I know where is the problem.

See you

**Comment by chiqui3d** [comment]
Okay, I've reboot my PC and now it works, :(.
Two strange things I see, and I want to know if you can help me.

1- Before the response of the controller of a list of users was an array, and now it seems that it returns me an array but with the keys. I don't understand why this happens. 

2-I ask before asking directly in TypeORM, but the listener of an entity does not work for me, I do not know if it has to do with TSED or directly with TypeORM. I put the entity:

```ts
import {IgnoreProperty, Required} from '@tsed/common'
import {Description} from '@tsed/swagger'
import {
    AfterInsert,
    AfterUpdate,
    BeforeInsert,
    BeforeUpdate,
    Column,
    CreateDateColumn,
    Entity,
    PrimaryGeneratedColumn,
    Unique
} from 'typeorm'
import {Roles} from '@src/Enum/Roles'

@Entity()
@Unique(['username', 'email'])
export class User {

    @Description('Database assigned id')
    @PrimaryGeneratedColumn()
    id: number

    @Description('User username')
    @Column()
    @Required()
    username: string

    @Description('User email')
    @Column()
    @Required()
    email: string

    @Description('User image')
    @Column({nullable: true})
    image: string

    @Description('User first name')
    @Column()
    @Required()
    firstName: string

    @Description('User last name')
    @Column()
    @Required()
    lastName: string

    @Description('User password')
    @IgnoreProperty()
    @Column('longtext')
    @Required()
    password: string

    @Description('User country')
    @Column({nullable: true})
    country: string

    @IgnoreProperty()
    @Column({default: 0})
    enabled: boolean

    @Description('Roles data')
    @Column({
        type: 'set',
        enum: Roles,
        default: [Roles.CUSTOMER]
    })
    roles: Roles[]

    @Description('User created date')
    @CreateDateColumn()
    createdAt: Date

    @BeforeInsert()
    beforeInsert() {
        console.log('beforeInsert')
        this.username = this.setUsername()
    }

    @BeforeUpdate()
    beforeUpdate() {
        console.log('BeforeUpdate')
        this.username = this.setUsername()
    }

    @AfterUpdate()
    afterUpdate() {
        console.log('afterUpdate')
        this.username = this.setUsername()
    }

    @AfterInsert()
    afterInsert() {
        console.log('AfterInsert')
        this.username = this.setUsername()
    }

    setUsername() {
        console.log('setUsername asd')
        return this.username.trim().toLowerCase()
    }

}
```

**Comment by chiqui3d** [comment]
ok, I know why he was showing me the error ConverterService.

It was because I was using the `User entity` as type in the parameters and I was sending via **Ajax** also **confirmPassword**, which does not **pertain** to the User entity, lol...

About the `listener ` still doesn't work, but I've solved it with Subscriptions.

```ts
import {EntitySubscriberInterface, EventSubscriber, InsertEvent, UpdateEvent} from "typeorm"
import {User} from "@src/Entity/User"
const bcrypt = require('bcrypt');

@EventSubscriber()
export class PostSubscriber implements EntitySubscriberInterface<User> {


    /**
     * Indicates that this subscriber only listen to Post events.
     */
    listenTo() {
        return User;
    }

    /**
     * Called before post insertion.
     */
    beforeUpdate(event: UpdateEvent<User>) {
        event.entity.username = event.entity.username.replace(/\s/g, '').toLowerCase();
    }
    /**
     * Called before post insertion.
     */
    beforeInsert(event: InsertEvent<User>) {
        const saltRounds = 10;
        const myPlaintextPassword = event.entity.password;
        event.entity.password = bcrypt.hashSync(myPlaintextPassword, saltRounds);
    }

}
```

**Comment by chiqui3d** [comment]
I also failed ConverterService with Type `number`

`remove (@PathParams('id') id: number): Promise<User[]> {`

**Comment by Romakita** [comment]
@chiqui3d Are you sure isn't related to the User entity? Because error could from TypeORM entity and converterService.
Can you provide me a small repo with the reproductible error, please :) ?

**Comment by chiqui3d** [comment]
remove (@PathParams('id') id: number): Promise<User[]> {
What does `number `have to do with `User`?

**Comment by chiqui3d** [comment]
here other error: 

```
Error 400. Bad request on parameter "request.body". Conversion failed for 
class "User" with object =>

 {"username":"javierperez","email":"mama@gmail.com","firstName":"mama",
"lastName":"mama","country":"ES","license":"asdasdasd","roles":["CUSTOMER"]}. 

Error for roles with value ["CUSTOMER"] Conversion failed for class "Array" with object => 
["CUSTOMER"]. Cannot read property 'deserialize' of undefined
```

**Comment by Romakita** [comment]
@chiqui3d is possible to have an access to your project. You give a lot of different issues but I haven’t a real usecase to reproduce the bug. 
Is not easy for to help you if you ask me for multiple problems ^^

See you
Romain

**Comment by chiqui3d** [comment]
ok!

I'm going to clone TypeORM Kit with a reproducible example.

Thank you.

**Comment by Romakita** [comment]
Ok thanks ;).

**Comment by chiqui3d** [comment]
I started testing on another clean project and everything worked, then I went back to my project and everything worked perfectly(very stranger). Honestly not what to tell you, just sorry about my reports, now I am finally working with pleasure.

So I can only report `@NotSerialize()`, which is really `@IgnoreProperty` at https://tsed.io/docs/converters.html#serialisation, in the last example of that section.

And just a doubt based on https://tsed.io/docs/converters.html#converters, I think there should be an example with Promise<User>, I really don't know if it like works, but the only way to make the converter work in a promise as a return is to put the decorator `@Returns(User)`. Example:

```ts
  @Post('/update/:id')
  @Description('Update user by ID')
  @Returns(User)
  async update (@PathParams('id') id: number, @BodyParams() body: User): Promise<User> {
    const user = await this.userRepository.findOne(id)
    if (!user) {
      throw new NotFound('Not user found')
    }
    return this.userRepository.save({...user,...body})
  }
```

Little by little I'm seeing the way. Thank you very much and great work.

**Comment by chiqui3d** [comment]
Exactly in that particular case, in this case it works perfectly:

```
  @Post('/')
  @Description('List users')
  async index (@Req() request: Express.Request): Promise<User[]> {
    const users = await this.userRepository.find()
    if (!users) {
      throw new NotFound('Not users found')
    }
    return users;
  }
```

But the example of `Returns(User) `would be ideal in the converters section.

**Comment by Romakita** [comment]
I added a example with Returns() on converter page :)
