### ISSUE TITLE
[BUG] [Minor] Cant have socket service inside mounts folders

### ISSUE THREAD

**Issue by angusmunro** [TypedProject/tsed#789]
This is a minor bug, but I thought I'd report it so if anyone else googles "provider.getEndpointUrl is not a function" they will know the fix ;-). Thanks again for this library, it's amazing!

#  Information

- **Version:** 5.44.13
- Packages: @tsed/socketio

## Example

use socketio example from tsed source and move the SquareGameService into the controllers/pages or controllers/rest folder.

Basically any folder specified in  

mount: {
    "/": `${rootDir}/controllers/pages/**/*.ts`,
    "/rest": `${rootDir}/controllers/rest/**/*.ts`
  },

### Error thrown
```
TypeError: provider.getEndpointUrl is not a function
    at Platform.addRoute (/Users/xxx/Documents/source/tsed/tsed/examples/socketio/node_modules/@tsed/common/src/platform/services/Platform.ts:77:30)
    at /Users/xxx/Documents/source/tsed/tsed/examples/socketio/node_modules/@tsed/common/src/platform/services/Platform.ts:68:12
    at Array.forEach (<anonymous>)
    at Platform.addRoutes (/Users/xxx/Documents/source/tsed/tsed/examples/socketio/node_modules/@tsed/common/src/platform/services/Platform.ts:67:12)
    at Server.<anonymous> (/Users/xxx/Documents/source/tsed/tsed/examples/socketio/node_modules/@tsed/common/src/server/components/ServerLoader.ts:430:14)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/Documents/source/tsed/tsed/examples/socketio/node_modules/tslib/tslib.js:110:62)
```

## Acceptance criteria

- Should be able to decorate a service with @SocketService inside these folders
OR
- Documentation should make it clear this isn't OK

This previously didn't cause an error in V 5.1.1

## Workaround
Simply use different folders for your socket services..

**Comment by Romakita** [comment]
Ha ok I see :)
Thanks for the report

**Comment by Romakita** [comment]
Fixed :)

**Comment by angusmunro** [comment]
Awesome! Thanks
