### ISSUE TITLE
[BUG] Cannot read property 'container' of undefined

### ISSUE THREAD

**Issue by chiqui3d** [TypedProject/tsed#792]
## Information

- **Version:** 5.44.14
- **OS:** Windows 10

Full error:

 
```sh
TypeError: Cannot read property 'container' of undefined
    at HandlerContext.get container [as container] (G:\www\api-profit-new\app\api\node_modules\@tsed\common\src\platform\domain\Handl
erContext.ts:34:29)
    at HandlerContext.<anonymous> (G:\www\api-profit-new\app\api\node_modules\@tsed\common\src\platform\domain\HandlerContext.ts:110:
60)
    at Generator.next (<anonymous>)
    at G:\www\api-profit-new\app\api\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (G:\www\api-profit-new\app\api\node_modules\tslib\tslib.js:109:16)
    at HandlerContext.callHandler (G:\www\api-profit-new\app\api\node_modules\@tsed\common\lib\platform\domain\HandlerContext.js:71:2
4)
    at PlatformHandler.<anonymous> (G:\www\api-profit-new\app\api\node_modules\@tsed\common\src\platform\services\PlatformHandler.ts    at PlatformHandler.<anonymous> (G:\www\api-profit-new\app\api\node_modules\@tsed\common\src\platform\services\PlatformHandler.ts
:189:21)
    at Generator.next (<anonymous>)
    at G:\www\api-profit-new\app\api\node_modules\tslib\tslib.js:113:75
```

This happens to me from time to time, and it shows up on the `terminal`, without me doing anything weird.

**Comment by Romakita** [comment]
Hum interesting. It means, the HandlerContext is called after the response is sending.

I'll investigate :)

**Comment by chiqui3d** [comment]
I have to add: That the App goes on its way, it only shows that error, but I can keep making requests, all this in development mode, I still have nothing in production. But I wanted to report it because it could affect the best in the performance of the application in production. I really don't know.

Yesterday it appeared right after I made a request to this endpoint, I really don't know if it has to see anything.

```ts
    @Post('/')
    @Description('List users')
    async index(@Req() request: Express.Request): Promise<User[]> {
        const users= await this.userRepository.find()
        if (!users) {
            throw new NotFound('Not users found')
        }
        return users
    }
```
userRepository
```ts
import { Repository, EntityRepository } from 'typeorm'
import { User } from '@src/Entity/User'

@EntityRepository(User)
export class UserRepository extends Repository<User> {
}

```

**Comment by kirrie** [comment]
I have the same experience. it seems like that occurs when abort a request before receiving a response.
```javascript
@Controller('/ping')
export class PingController {
	@Get('/')
	async pong(): Promise<string> {
		return new Promise((resolve, reject) => {
			setTimeout(() => {
				return resolve('pong-v1.1');
			}, 5000);
		});
	}
}
```
In above controller, call /ping and abort a request at 2.5sec. you'll get the error.
