### ISSUE TITLE
problem for start

### ISSUE THREAD

**Issue by marefati110** [TypedProject/tsed#810]
i use ```tsed init .``` then select database(sqlite) and swagger after installing package start with this command ```yarn start```
i get this error
why ??
```bash
[2020-04-27T14:09:43.129] [ERROR] [TSED] - TypeError: Cannot read property 'name' of undefined
    at TypeORMService.<anonymous> (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/src/services/TypeORMService.ts:31:26)
    at Generator.next (<anonymous>)
    at /home/ali/file/psycholingo_d-master.tar.gz/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/tslib/tslib.js:109:16)
    at TypeORMService.createConnection (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/lib/services/TypeORMService.js:30:24)
    at /home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/src/TypeORMModule.ts:13:80
    at Array.map (<anonymous>)
    at TypeORMModule.<anonymous> (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/src/TypeORMModule.ts:13:49)
    at Generator.next (<anonymous>)
(node:6165) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at TypeORMService.<anonymous> (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/src/services/TypeORMService.ts:31:26)
    at Generator.next (<anonymous>)
    at /home/ali/file/psycholingo_d-master.tar.gz/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/tslib/tslib.js:109:16)
    at TypeORMService.createConnection (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/lib/services/TypeORMService.js:30:24)
    at /home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/src/TypeORMModule.ts:13:80
    at Array.map (<anonymous>)
    at TypeORMModule.<anonymous> (/home/ali/file/psycholingo_d-master.tar.gz/node_modules/@tsed/typeorm/src/TypeORMModule.ts:13:49)
    at Generator.next (<anonymous>)
(node:6165) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:6165) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Romakita** [comment]
Hello @marefati110 
I fixed this issue yesterday. The cli forgot to add a `name` field in the generated typeorm conf.
To solve your issue simply add `name: 'default'` in your `typeorm/default.config.json`.

See you
Romain

**Comment by Romakita** [comment]
The latest version of the CLI generate the right typeorm configuration.

**Comment by marefati110** [comment]
@Romakita thanks for your help
i update cli and build new project and checked the```name:"default"``` exist but i have same error 

typeorm/default.config.json.
```json
{
  "name": "default",
  "type": "sqlite",
  "database": "database.sqlite",
  "synchronize": true,
  "logging": false,
  "entities": [
    "${rootDir}/entity/**/*.ts"
  ],
  "migrations": [
    "${rootDir}/migration/**/*.ts"
  ],
  "subscribers": [
    "${rootDir}/subscriber/**/*.ts"
  ],
  "cli": {
    "entitiesDir": "${rootDir}/entity",
    "migrationsDir": "${rootDir}/migration",
    "subscribersDir": "${rootDir}/subscriber"
  }
}
```

**Comment by marefati110** [comment]
hello again

i start new project with mongodb database now i have this error

```bash
home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:423
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/config/mongoose/default.config.ts:2:8 - error TS7031: Binding element 'process' implicitly has an 'any' type.

2   url: process.env.DEFAULT_URL || "mongodb://localhost:27017/default",
         ~~~~~~~
src/config/mongoose/default.config.ts:2:16 - error TS7031: Binding element 'env' implicitly has an 'any' type.

2   url: process.env.DEFAULT_URL || "mongodb://localhost:27017/default",
                 ~~~
src/config/mongoose/default.config.ts:2:20 - error TS7031: Binding element 'DEFAULT_URL' implicitly has an 'any' type.

2   url: process.env.DEFAULT_URL || "mongodb://localhost:27017/default",
                     ~~~~~~~~~~~
src/config/mongoose/default.config.ts:2:32 - error TS2695: Left side of comma operator is unused and has no side effects.

2   url: process.env.DEFAULT_URL || "mongodb://localhost:27017/default",
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/config/mongoose/default.config.ts:3:3 - error TS2304: Cannot find name 'connectionOptions'.

3   connectionOptions: {
    ~~~~~~~~~~~~~~~~~
src/config/mongoose/default.config.ts:4:22 - error TS2695: Left side of comma operator is unused and has no side effects.

4     useNewUrlParser: true,
                       ~~~~
src/config/mongoose/default.config.ts:5:5 - error TS2304: Cannot find name 'useUnifiedTopology'.

5     useUnifiedTopology: true
      ~~~~~~~~~~~~~~~~~~
src/config/mongoose/default.config.ts:1:14 - error TS1134: Variable declaration expected.

1 export const default = {
               ~~~~~~~
src/config/mongoose/default.config.ts:1:22 - error TS1134: Variable declaration expected.

1 export const default = {
                       ~
src/config/mongoose/default.config.ts:2:15 - error TS1005: ',' expected.

2   url: process.env.DEFAULT_URL || "mongodb://localhost:27017/default",
                ~
src/config/mongoose/default.config.ts:2:19 - error TS1005: ',' expected.

2   url: process.env.DEFAULT_URL || "mongodb://localhost:27017/default",
                    ~
src/config/mongoose/default.config.ts:2:32 - error TS1005: ',' expected.

2   url: process.env.DEFAULT_URL || "mongodb://localhost:27017/default",
                                 ~~
src/config/mongoose/default.config.ts:3:20 - error TS1005: ';' expected.

3   connectionOptions: {
                     ~
src/config/mongoose/default.config.ts:5:23 - error TS1005: ';' expected.

5     useUnifiedTopology: true
                        ~
src/config/mongoose/default.config.ts:7:1 - error TS1128: Declaration or statement expected.

7 }
  ~

    at createTSError (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:423:12)
    at reportTSError (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:427:19)
    at getOutput (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:554:36)
    at Object.compile (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:760:32)
    at Module.m._compile (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:839:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:842:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/ali/file/psycholingo-back-end/src/config/mongoose/index.ts:2:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:839:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ali/file/psycholingo-back-end/node_modules/ts-node/src/index.ts:842:12)
```

there is a problem with default

in server.ts replace this and it worked :)

```javascript
  mongoose: {
    url: process.env.mongoose_url || "mongodb://127.0.0.1:27017/example-mongoose-test",
    connectionOptions: {
      useNewUrlParser: true,
      useUnifiedTopology: true
    }
```

**Comment by ben-checkfer** [comment]
I also had this issue on a fresh project created with `tsed init` with postgres - it looks like the `default.config.json` file is not imported properly in `src/conifg/typeorm/index.ts`, I copied the JSON into `src/config/typeorm/index.ts` directly and it worked
