### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by brandonpas** [TypedProject/tsed#848]
## Information

- **Version:** 5.57.6
- Packages: 
    @tsed/common
    @tsed/core
    @tsed/di
    @tsed/exceptions
    @tsed/platform-express
    @tsed/swagger
    @tsed/testing
    @tsed/typeorm
    @types/express
    jest

I'm following the documentation for testing the Rest API using supertest and encountering an error when the test is run:

```
FAIL test/controllers/UserController.test.ts (5.122 s)
  UserController.test
    GET /rest/user
      × should return successfully (2 ms)

  ● UserController.test › GET /rest/user › should return successfully

    TypeError: platformBuildClass is not a constructor

      at Function.build (node_modules/@tsed/common/src/platform-builder/builder/PlatformBuilder.ts:70:12)
      at Object.before (node_modules/@tsed/common/src/platform-test/components/PlatformTest.ts:70:42)

  ● UserController.test › GET /rest/user › should return successfully

    PlatformTest.injector is not initialized. Use PlatformTest.create(): Promise before PlatformTest.invoke() or PlatformTest.injector.
    Example:
    before(async () => {
       await PlatformTest.create()
       await PlatformTest.invoke(MyService, [])
    })

      42 |   beforeAll(PlatformTest.bootstrap(Server));
      43 |   beforeAll(() => {
    > 44 |     request = SuperTest(PlatformTest.callback());
         |                                      ^
      45 |   });
      46 |   afterAll(PlatformTest.reset);
      47 |

      at Function.get injector [as injector] (node_modules/@tsed/common/src/platform-test/components/PlatformTest.ts:23:11)
      at Function.callback (node_modules/@tsed/common/src/platform-test/components/PlatformTest.ts:174:25)
``` 

### Server.ts
```
import 'reflect-metadata';
import Path = require("path");
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const compress = require('compression');
const methodOverride = require('method-override');
import { GlobalAcceptMimesMiddleware, Inject, Configuration, PlatformApplication, ServerLoader, ServerSettings} from "@tsed/common";
import { UserController } from './controllers/UserController';
export const rootDir = __dirname;

@Configuration({
  version: "1.0.1",
  rootDir: Path.resolve(__dirname),
  httpPort: 8080,
  mount: {
    "/rest": [UserController]
  },
  acceptMimes: ["application/json"],
  componentsScan: [
    `${rootDir}/services/*{.ts,.js}`,
    `${rootDir}/repositories/*{.ts,.js}`,
  ],
  swagger: [
    {
      path: "/api-docs"
    }
  ]
})
export class Server {

  constructor(
    @Inject(PlatformApplication) public app: PlatformApplication) {
  }

  @Configuration()
  settings!: Configuration;

    public $beforeRoutesInit(): void|Promise<any> {
      this.app
          .use(GlobalAcceptMimesMiddleware)
          .use(cookieParser())
          .use(compress({}))
          .use(methodOverride())
          .use(bodyParser.json())
          .use(bodyParser.urlencoded({
              extended: true
          }));
  }

  public $onReady(){
      console.log('Server started...');
  }
 
  public $onServerInitError(err: Error){
      console.error(err);
  }  

}

```

### UserController.ts
```
import * as Express from 'express';
import { Controller, Get, Res, Status } from '@tsed/common';
import { UserContractResponse } from './contracts/UserContractResponse';
import {Returns } from '@tsed/swagger'

@Controller("/user")
export class UserController {
  @Get("/:id")
  @Status(201)
  @Returns(UserContractResponse)
  async getUser(@Res() response: Express.Response) {
    return response
        .status(201)
        .send({id: 24, name: "test"});
  }
}

```

### UserController.test.ts
```
import { PlatformTest } from "@tsed/common";
import { Server } from "../../src/Server";
import SuperTest from 'supertest';
import { expect } from "chai";
import { TestContext } from '@tsed/testing';

describe('UserController.test', () => {

  let request: SuperTest.SuperTest<SuperTest.Test>;
  beforeAll(PlatformTest.bootstrap(Server));
  beforeAll(() => {
    request = SuperTest(PlatformTest.callback());
  });
  afterAll(PlatformTest.reset);

  describe("GET /rest/user", () => {

    test.only('should return successfully', async () => {
      
      const response = await request.get('/rest/user/2').expect(200);

    });
  });

});
```

**Comment by Romakita** [comment]
You have to add `import "@tsed/platform-express"` on your Server.ts. This line tell PlatformTest which platform must be used to run unit and integration test :)

**Comment by brandonpas** [comment]
You are wonderful! That was exactly the issue.

**Comment by Romakita** [comment]
Yep. I know this error, I'll add a message when an error occurs on this part ;).

**Comment by pryme0** [comment]
This didn't work for me  i already have  "@tsed/platform-express" imported  but i am still getting an error message that reads

`PlatformTest.injector is not initialized. Use PlatformTest.create(): Promise before PlatformTest.invoke() or PlatformTest.injector.`

**Comment by Romakita** [comment]
Create a reproducible example please (repo). Generally, the problem is related to the framework itself (circular ref, wrong import, missing config, etc…)

**Comment by pryme0** [comment]
@Romakita  it was the tsconfig file i was passing to ts-jest...when in pointed it to the correct file it worked

**Comment by pryme0** [comment]
Thanks
