### ISSUE TITLE
[BUG] Jest testing won't open database connection.

### ISSUE THREAD

**Issue by bpofficial** [TypedProject/tsed#864]
## Information

- **Version:** 5.x
- Packages: 
```
"@tsed/common": "^5.58.1",
"@tsed/core": "^5.58.1",
"@tsed/di": "^5.58.1",
"@tsed/exceptions": "^5.58.1",
"@tsed/passport": "^5.58.1",
"@tsed/platform-express": "^5.58.1",
"@tsed/swagger": "^5.58.1",
"@tsed/testing": "^5.58.1",
"@tsed/typeorm": "^5.58.1",
"body-parser": "^1.19.0",
"class-validator": "^0.12.2",
"compression": "^1.7.4",
"cookie-parser": "^1.4.5",
"cors": "^2.8.5",
"dotenv": "^8.0.0",
"express": "^4.17.1",
"helmet": "^3.23.1",
"http-status-codes": "^1.4.0",
"jsonwebtoken": "^8.5.1",
"method-override": "^3.0.0",
"mjml": "^4.6.3",
"moment": "^2.27.0",
"mysql": "^2.18.1",
"nodemailer": "^6.4.10",
"passport": "^0.4.1",
"passport-cookie": "^1.0.8",
"passport-google-oauth20": "^2.0.0",
"passport-jwt": "^4.0.0",
"passport-local": "^1.0.0",
"passport-oauth2-refresh": "^2.0.0",
"typeorm": "^0.2.25",
"uuid": "^8.2.0"
```

A few sentences describing the overall goals of the issue.

Jest @Service testing refuses to provide an open mysql connection.
```
import {PlatformTest} from '@tsed/common';
import {Server} from '../../src/Config/api';

describe('Testing Suite', () => {
	beforeEach(PlatformTest.bootstrap(Server));
	afterEach(PlatformTest.reset);
        
    it(
        'Should create a customer',
	PlatformTest.inject(
	    [serviceClass],
	    async (service: serviceClass) => {
                await service.getOne(1);
            }
        )
    )
});
```

Error received:
```
Pool is closed.

      at node_modules/mysql/lib/Pool.js:149:17
          at Array.forEach (<anonymous>)
      at Pool.releaseConnection (node_modules/mysql/lib/Pool.js:148:37)
      at Pool.Object.<anonymous>.Pool._removeConnection (node_modules/mysql/lib/Pool.js:277:8)
      at Pool._purgeConnection (node_modules/mysql/lib/Pool.js:258:8)
      at Ping.onOperationComplete (node_modules/mysql/lib/Pool.js:101:12)
      at Ping.<anonymous> (node_modules/mysql/lib/Connection.js:526:10)
      at Ping._callback (node_modules/mysql/lib/Connection.js:488:16)
      at Ping.Object.<anonymous>.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
      at Ping.Object.<anonymous>.Sequence.OkPacket (node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
```

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @bpofficial 
I don't know how I can help you. This is a problem between jest and TypeORM. 
Is use a memory database to test with typeorm and there is no issue. 

If think this problem must be reported to TypeORM project. It's not related to Ts.ED

See you
Romain

**Comment by Romakita** [comment]
Or replace beforeEach, afterEach by beforeAll, afterAll

**Comment by bpofficial** [comment]
I didn't even think of TypeORM, I'll submit a new issue on their repo. Can confirm that changing beforeEach to beforeAll etc. doesn't work. 

Cheers,
Brayden :)

**Comment by bpofficial** [comment]
Solved this, the error is thrown after tests have (successfully or not) run when using `PlatformTest.reset`.
