### ISSUE TITLE
[QUESTION] Setup for Mongoose 

### ISSUE THREAD

**Issue by paschaldev** [TypedProject/tsed#873]
I followed the guide in setting up Mongoose but app keeps crashing with this error

```
[nodemon] starting `ts-node src/index.ts`
[2020-07-09T02:05:04.580] [ERROR] [TSED] - TypeError: common_1.PropertyMetadata.getProperties is not a function
    at buildMongooseSchema (/Users/p/dev/node_modules/@tsed/mongoose/src/utils/createSchema.ts:70:39)
    at createSchema (/Users/p/dev/node_modules/@tsed/mongoose/src/utils/createSchema.ts:45:30)
    at Object.getSchema (/Users/p/dev/node_modules/@tsed/mongoose/src/utils/createSchema.ts:58:32)
    at /Users/p/dev/node_modules/@tsed/mongoose/src/decorators/model.ts:51:20
    at DecorateConstructor (/Users/p/dev/node_modules/reflect-metadata/Reflect.js:541:33)
    at Object.decorate (/Users/p/dev/node_modules/reflect-metadata/Reflect.js:130:24)
    at __decorate (/Users/p/dev/src/database/models/User.ts:4:92)
    at Object.<anonymous> (/Users/p/dev/src/database/models/User.ts:8:23)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module.m._compile (/Users/p/dev/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/p/dev/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
[nodemon] app crashed - waiting for file changes before starting...
```

### src/models/User.ts
```ts
import { Required } from '@tsed/common'
import { Model, ObjectID } from '@tsed/mongoose'

@Model({
  collection: 'users',
})
export class UserModel  {
  @ObjectID('id')
  _id: string

  @Required()
  firstName: string

  @Required()
  lastName: string
}
```

I do not know what I'm doing wrong

**Comment by Romakita** [comment]
Hello @paschaldev 
Have you the same version for @tsed/common and @tsed/mongoose ?

**Comment by paschaldev** [comment]
@Romakita Thanks very much. That fixed it. Spent hours finding the problem lol

**Comment by Romakita** [comment]
Sorry about that :). Keep in mind, you must always have the same package version for all @tsed/* packages ;)

**Comment by Romakita** [comment]
you can use the command `tsed update` for that ^^

**Comment by paschaldev** [comment]
Thanks I'll start paying attention to that. I have on new challenge. Is it possible to get the current `moongoose` connection outside the context of a class / di.

I need to access the connection in a bare function without a `constructor`, so I cannot inject `MongooseService`. Any way around this?

**Comment by Romakita** [comment]
Hum to doing that, you just have to use mongoose.createConnection() :)

**Comment by paschaldev** [comment]
Okay thanks
