### ISSUE TITLE
[BUG] Cannot assign to read only property 'username' of object '#<AddAccountModel>

### ISSUE THREAD

**Issue by chopachom** [TypedProject/tsed#883]
## Information

- **Version:** 5.61.1
- Packages: 
    "@tsed/ajv": "^5.61.1",
    "@tsed/common": "^5.61.1",
    "@tsed/core": "^5.61.1",
    "@tsed/di": "^5.61.1",
    "@tsed/platform-express": "^5.61.1",

I'm trying to run my first project using ts.ed but I have this problem right from the start, I have a controller that should accept simple model, but it fails with this error:

```

[2020-07-23T11:43:35.132] [INFO ] [TSED] - Call hook $beforeInit
[2020-07-23T11:43:35.134] [INFO ] [TSED] - Call hook $onInit
[2020-07-23T11:43:35.134] [INFO ] [TSED] - Build providers
[2020-07-23T11:43:35.163] [INFO ] [TSED] - Call hook $afterInit
[2020-07-23T11:43:35.164] [INFO ] [TSED] - Load routes
[2020-07-23T11:43:35.164] [INFO ] [TSED] - Call hook $beforeRoutesInit
[2020-07-23T11:43:35.166] [INFO ] [TSED] - Call hook $onRoutesInit
[2020-07-23T11:43:35.166] [INFO ] [TSED] - Call hook $afterRoutesInit
[2020-07-23T11:43:35.166] [INFO ] [TSED] - Routes mounted :
[2020-07-23T11:43:35.167] [INFO ] [TSED] - 
┌────────────────┬──────────────┬───────────────────────────────────┐
│ Method         │ Endpoint     │ Class method                      │
│────────────────│──────────────│───────────────────────────────────│
│ POST           │ /account/add │ AddAccountCtrl.actionAddAccount() │
└────────────────┴──────────────┴───────────────────────────────────┘
[2020-07-23T11:43:35.167] [INFO ] [TSED] - Call hook $beforeListen
[2020-07-23T11:43:35.172] [INFO ] [TSED] - Listen server on http://0.0.0.0:3001
[2020-07-23T11:43:35.173] [INFO ] [TSED] - Listen server on https://0.0.0.0:8000
[2020-07-23T11:43:35.173] [INFO ] [TSED] - Call hook $afterListen
[2020-07-23T11:43:35.173] [INFO ] [TSED] - Call hook $onReady
[2020-07-23T11:43:35.173] [INFO ] [TSED] - Started in 66 ms
~~~~~~~~~~ { username: 'john', password: 'secret' }
[2020-07-23T11:44:15.997] [INFO ] [TSED] - {
  reqId: '9fa8328609864d1d876615c05cec7eef',
  method: 'POST',
  url: '/account/add',
  duration: 2,
  time: 2020-07-23T07:44:15.997Z,
  event: 'request.start'
}
[2020-07-23T11:44:16.038] [INFO ] [TSED] - {
  reqId: '9fa8328609864d1d876615c05cec7eef',
  method: 'POST',
  url: '/account/add',
  duration: 43,
  time: 2020-07-23T07:44:16.038Z,
  event: 'request.end',
  status: 500
}
[2020-07-23T11:44:16.034] [ERROR] [TSED] - {
  method: 'POST',
  url: '/account/add',
  headers: {
    'content-type': 'application/json',
    'content-length': '49',
    host: 'localhost:3001',
    connection: 'Keep-Alive',
    'user-agent': 'Apache-HttpClient/4.5.12 (Java/11.0.7)',
    'accept-encoding': 'gzip,deflate'
  },
  body: undefined,
  query: {},
  params: {},
  reqId: '9fa8328609864d1d876615c05cec7eef',
  time: 2020-07-23T07:44:16.034Z,
  duration: 39,
  error: {
    status: 500,
    message: "Cannot assign to read only property 'username' of object '#<AddAccountModel>'",
    stack: "TypeError: Cannot assign to read only property 'username' of object '#<AddAccountModel>'\n" +
      '    at ConverterService.convertProperty (/private/var/www/tt-web-automation/node_modules/@tsed/common/src/converters/services/ConverterService.ts:261:28)\n' +
      '    at /private/var/www/tt-web-automation/node_modules/@tsed/common/src/converters/services/ConverterService.ts:192:19\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at ConverterService.deserialize (/private/var/www/tt-web-automation/node_modules/@tsed/common/src/converters/services/ConverterService.ts:189:22)\n' +
      '    at AjvValidationPipe.validateFromModel (/private/var/www/tt-web-automation/node_modules/@tsed/ajv/src/pipes/AjvValidationPipe.ts:80:37)\n' +
      '    at AjvValidationPipe.transform (/private/var/www/tt-web-automation/node_modules/@tsed/ajv/src/pipes/AjvValidationPipe.ts:27:12)\n' +
      '    at /private/var/www/tt-web-automation/node_modules/@tsed/common/src/platform/services/PlatformHandler.ts:212:59\n' +
      '    at handleError (/private/var/www/tt-web-automation/node_modules/@tsed/common/src/platform/services/PlatformHandler.ts:203:22)\n' +
      '    at /private/var/www/tt-web-automation/node_modules/@tsed/common/src/platform/services/PlatformHandler.ts:212:14\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
    origin: undefined
  }
}
```

## Example

```typescript
import {$log, BodyParams, Configuration, Controller, Inject, Pattern, PlatformApplication, Post, Required} from "@tsed/common";
import {GlobalAcceptMimesMiddleware, PlatformExpress} from "@tsed/platform-express";
import "@tsed/ajv";
import * as bodyParser from "body-parser";
import * as compress from "compression";
import * as cookieParser from "cookie-parser";
import * as methodOverride from "method-override";
import * as express from 'express';

const rootDir = __dirname;

class AddAccountModel {
  @Required
  @Pattern(/[a-zA-Z0-9]/)
  username!: string;

  @Required
  password!: string;
}

@Controller("/account")
class AddAccountCtrl {
  @Post('/add')
  actionAddAccount(@BodyParams() request: AddAccountModel): string {
    console.log(1);
    return "success";
  }
}


@Configuration({
  rootDir,
  acceptMimes: ["application/json"],
  mount: {
    '/': [
      AddAccountCtrl
    ]
  }
})
class Server {
  @Inject()
  app!: PlatformApplication;

  @Configuration()
  settings!: Configuration;

  /**
   * This method let you configure the express middleware required by your application to works.
   * @returns {Server}
   */
  public $beforeRoutesInit(): void | Promise<any> {

    this.app
      .use(GlobalAcceptMimesMiddleware) // optional
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({
        extended: true
      }))
      .use((req: express.Request, res: express.Response, next: express.NextFunction) => {
        console.log('~~~~~~~~~~', req.body)
        next();
      })
  }
}


async function bootstrap() {
  try {
    $log.debug("Start server...");
    const platform = await PlatformExpress.bootstrap(Server, {
      port: 3001
      // extra settings
    });

    await platform.listen();
    $log.debug("Server initialized");
  } catch (er) {
    $log.error(er);
  }
}

bootstrap().catch(err => {
  console.error('Bootstrap error:', err);
  process.exit(1);
});

```

**Comment by Romakita** [comment]
Hello @chopachom 

Is it normal to not have parenthesis with the Required() decorator ?
```typescript
class AddAccountModel {
  @Required // here. For me, it must have parenthesis (it's not optional)
  @Required() // OK
  @Pattern(/[a-zA-Z0-9]/)
  username!: string;

  @Required()
  password!: string;
}
```

This is only error I can see your example. For me your code is ok. I'll try to reproduce it :)

Romain

**Comment by Romakita** [comment]
I confirm your bug is related to the missing parenthesis :)

I added a working example repository ;)
https://github.com/Romakita/tsed-issue-883

See you
Romain

**Comment by chopachom** [comment]
Oh, so sorry for taking your time with such lame typo =( Yes, it were parenthesis
