### ISSUE TITLE
Can't run different microservices on different ports

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/tsed#885]
Hi,

I'm working on microservices which I'd like to run simultaneously locally.
Each microservice is using TSED, and each is running on a different port (which I'm passing to @ServerSettings).

However when I tried to actually run each microservice on a different port, I noticed they run not only on that port, but also on an additional port - 8000. I'm not sure how to change that additional port.

For instance, let's say I have 2 microservices: Apps and Users.

I'm trying to run Apps on port 8080, and Users on port 8081.

When running Apps, I get the following output in the logs:
```
[2020-07-24T01:12:08.191] [INFO ] [Apps] - Listen server on http://0.0.0.0:8080
[2020-07-24T01:12:08.191] [INFO ] [Apps] - Listen server on https://0.0.0.0:8000
```

When running Users, I get the following output in the logs:
```
[2020-07-24T01:07:57.378] [INFO ] [Users] - Listen server on http://0.0.0.0:8081
[2020-07-24T01:07:57.380] [INFO ] [Users] - Listen server on https://0.0.0.0:8000
```

When I try to run Apps and then Users, this is the output I get in Users logs:

```
Listen server on http://0.0.0.0:8081
[2020-07-24T01:14:52.771] [ERROR] [Users] - Error: listen EADDRINUSE: address already in use 0.0.0.0:8000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8000
}
```

Which is to be expected since both are trying to run on port 8000.

What's the purpose behind running on port 8000 in addition to the original port?
Is there a way to change it?

**Comment by Romakita** [comment]
Hello @royibernthal 
Just set httpsPort: false. It’ll disable the https server ;)

**Comment by royibernthal** [comment]
Hey @Romakita 
Thanks for the quick reply, got it :)
