### ISSUE TITLE
[QUESTION] Cannot use Injectable that is updated in Middleware

### ISSUE THREAD

**Issue by vemundeldegard** [TypedProject/tsed#909]
I have a problem using a service (injectable) in another service when one service is updated in a middleware... I get no errors when server is built, only when I run route. I get this error when i run `GET /rest/hello`:

```sh
{
  method: 'GET',
  url: '/rest/hello',
  headers: {
    'user-agent': 'PostmanRuntime/7.24.1',
    accept: '*/*',
    'cache-control': 'no-cache',
    'postman-token': '6cad59fc-adbc-4758-94f3-d21f234d01c0',
    host: 'localhost:2222',
    'accept-encoding': 'gzip, deflate, br',
    connection: 'keep-alive'
  },
  body: {},
  query: {},
  params: {},
  reqId: 'cc9c40943b4a480589face182961ec0b',
  time: 2020-09-04T19:50:31.297Z,
  duration: 37,
  error: {
    status: 500,
    message: 'Injection failed on OtherService\n' +
      'Origin: Unable to inject dependency. Given token is undefined. Have you enabled emitDecoratorMetadata in your tsconfig.json or decorated your class with @Injectable, @Service, ... decorator ?\n' +
      '\n' +
      'OtherService->constructor(authenticationService: AuthenticationService, \u001b[31muser\u001b[39m: undefined)\n' +
      '                                                                            \u001b[31m^‾‾‾\u001b[39m',
    stack: 'UNDEFINED_TOKEN_ERROR: Unable to inject dependency. Given token is undefined. Have you enabled emitDecoratorMetadata in your tsconfig.json or decorated your class with @Injectable, @Service, ... decorator ?\n' +
      '\n' +
      'OtherService->constructor(authenticationService: AuthenticationService, \u001b[31muser\u001b[39m: undefined)\n' +
      '                                                                            \u001b[31m^‾‾‾\u001b[39m\n' +
      '    at Map.mapInvokeOptions (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:606:13)\n' +
      '    at Map.resolve (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:536:74)\n' +
      '    at Map.invoke (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:214:23)\n' +
      '    at /Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:562:70\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Map.resolve (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:569:29)\n' +
      '    at Map.invoke (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:236:25)\n' +
      '    at Map.bindProperty (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:408:28)\n' +
      '    at /Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:359:16\n' +
      '    at Array.forEach (<anonymous>)',
    origin: UNDEFINED_TOKEN_ERROR: Unable to inject dependency. Given token is undefined. Have you enabled emitDecoratorMetadata in your tsconfig.json or decorated your class with @Injectable, @Service, ... decorator ?
    
    OtherService->constructor(authenticationService: AuthenticationService, user: undefined)
                                                                                ^‾‾‾
        at Map.mapInvokeOptions (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:606:13)
        at Map.resolve (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:536:74)
        at Map.invoke (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:214:23)
        at /Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:562:70
        at Array.map (<anonymous>)
        at Map.resolve (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:569:29)
        at Map.invoke (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:236:25)
        at Map.bindProperty (/Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:408:28)
        at /Users/vemundeldegard/aiflow/microservices/microsoft/node_modules/@tsed/di/src/services/InjectorService.ts:359:16
        at Array.forEach (<anonymous>) {
      name: 'UNDEFINED_TOKEN_ERROR'
    }
  }
}
```

I have a middleware that updated by UserService like so: 

```typescript
@Injectable()
@Scope(ProviderScope.REQUEST)
export class UserService {
	// Authenticated userId
	public id: number;
}
```

I want to use it like so in another service: 
```typescript
@Injectable()
@Scope(ProviderScope.REQUEST)
export class OtherService {
	
	constructor(private readonly authenticationService: AuthenticationService, private readonly user: UserService) {}

	async helloUser() {
		console.log("User", this.user);
	}
}
```

Which is used in a Controller like so:
```typescript
@Controller("/hello")
@Scope(ProviderScope.REQUEST)
@UseBefore(Authorized)
export class MailController {
	@Inject()
	private readonly other: OtherService;

        @Get()
	async sayHello() {
		return await this.other.helloUser();
	}
}
```

I have enabled emitDecoratorMetadata and the decorators are in place..

**Comment by Romakita** [comment]
Hello @vemundeldegard 
I'm sorry, I'd just seen this issue because it was tagged with question.

Have you again the problem?
If you change the controller implementation by this, it should work:
```typescript
@Controller("/hello")
@Scope(ProviderScope.REQUEST)
@UseBefore(Authorized)
export class MailController {
        constructor(private readonly other: OtherService){
        }

        @Get()
	async sayHello() {
		return await this.other.helloUser();
	}
}
```

See you
Romain

**Comment by pdeveltere** [comment]
hej @Romakita, we are trying to migrate from v7 to v8. And I have a similar error message. 
```
UNDEFINED_TOKEN_ERROR: Given token is undefined. Have you enabled emitDecoratorMetadata in your tsconfig.json or decorated your class with @Injectable, @Service, ... decorator ?
```

My server looks like this:
```
@Configuration(configuration)
export class Server {
  @Inject(http.Server)
  protected server: http.Server;

  @Inject()
  protected app: PlatformApplication<Express>;
```
how can I do this without @Inject?

**Comment by Romakita** [comment]
Hi @pdeveltere 

Please open another issue concerning the v8 version. This issue is obsolete and not related to the same version.

**Comment by Romakita** [comment]
@pdeveltere try to install `@tsed/platform-http` as dependencies. It’s probably a transitive issue. Package manager try to install a di package for @tsed/common and another for @tsed/plaform-http. Not sure why. Tell me if this solution solve your issue. 
If it’s ok, I’ll update the migration guide!
