### ISSUE TITLE
[BUG] Injected repo undefined when built

### ISSUE THREAD

**Issue by bpofficial** [TypedProject/tsed#919]
## Information

- **Version:** 5.65.0
- Packages: 
```json
"devDependencies": {
		"@tsed/cli-plugin-eslint": "1.17.0",
		"@tsed/cli-plugin-jest": "1.17.0",
		"@tsed/cli-plugin-passport": "1.17.0",
		"@tsed/cli-plugin-typeorm": "1.17.0",
		"@types/aws-sdk": "^2.7.0",
		"@types/bcrypt": "^3.0.0",
		"@types/compression": "^1.7.0",
		"@types/cookie-parser": "^1.4.2",
		"@types/cors": "^2.8.7",
		"@types/crypto-js": "^3.1.47",
		"@types/express": "^4.17.8",
		"@types/http-status-codes": "^1.2.0",
		"@types/image-size": "^0.8.0",
		"@types/jest": "^25.2.3",
		"@types/jsonwebtoken": "^8.5.0",
		"@types/lodash": "^4.14.161",
		"@types/method-override": "0.0.31",
		"@types/mime-types": "^2.1.0",
		"@types/mjml": "^4.0.4",
		"@types/moment": "^2.13.0",
		"@types/multer": "^1.4.4",
		"@types/multer-s3": "^2.7.7",
		"@types/mysql": "^2.15.15",
		"@types/node": "^12.12.54",
		"@types/node-fetch": "^2.5.7",
		"@types/nodemailer": "^6.4.0",
		"@types/passport": "^1.0.4",
		"@types/passport-google-oauth20": "^2.0.3",
		"@types/passport-jwt": "^3.0.3",
		"@types/passport-microsoft": "0.0.0",
		"@types/supertest": "^2.0.10",
		"@typescript-eslint/eslint-plugin": "^1.12.0",
		"@typescript-eslint/parser": "^1.12.0",
		"babel-loader": "^8.1.0",
		"concurrently": "5.3.0",
		"copy-webpack-plugin": "^5.1.2",
		"cross-env": "^7.0.2",
		"eslint": "^7.6.0",
		"eslint-config-prettier": "6.11.0",
		"eslint-plugin-prettier": "3.1.4",
		"husky": "4.2.5",
		"jest": "^26.0.0",
		"lint-staged": "10.2.11",
		"lodash": "^4.17.20",
		"nodemon": "^2.0.4",
		"prettier": "2.0.5",
		"supertest": "^4.0.2",
		"ts-jest": "^26.3.0",
		"ts-node": "^8.10.2",
		"tsconfig-paths": "^3.9.0",
		"tslint-config-prettier": "^1.18.0",
		"tslint-jest": "^1.0.5",
		"typedoc": "^0.17.8"
	},
	"dependencies": {
		"@tsed/ajv": "^5.65.0",
		"@tsed/common": "^5.65.0",
		"@tsed/core": "^5.65.0",
		"@tsed/di": "^5.65.0",
		"@tsed/exceptions": "^5.65.0",
		"@tsed/multipartfiles": "^5.65.0",
		"@tsed/passport": "^5.65.0",
		"@tsed/platform-express": "^5.65.0",
		"@tsed/testing": "^5.65.0",
		"@tsed/typeorm": "^5.65.0",
		"body-parser": "^1.19.0",
		"class-validator": "^0.12.2",
		"compression": "^1.7.4",
		"cookie-parser": "^1.4.5",
		"cors": "^2.8.5",
		"crypto-js": "^4.0.0",
		"dotenv": "^8.0.0",
		"express": "^4.17.1",
		"express-session": "^1.17.1",
		"helmet": "^3.23.3",
		"http-status-codes": "^1.4.0",
		"image-size": "^0.8.3",
		"ip-range-check": "^0.2.0",
		"jsonwebtoken": "^8.5.1",
		"method-override": "^3.0.0",
		"mime-types": "^2.1.27",
		"mjml": "^4.6.3",
		"moment": "^2.27.0",
		"multer": "^1.4.2",
		"multer-s3": "^2.9.0",
		"mysql": "^2.18.1",
		"node-fetch": "^2.6.0",
		"nodemailer": "^6.4.11",
		"passport": "^0.4.1",
		"passport-cookie": "^1.0.8",
		"passport-google-oauth20": "^2.0.0",
		"passport-jwt": "^4.0.0",
		"passport-local": "^1.0.0",
		"passport-microsoft": "^0.1.0",
		"passport-oauth2-refresh": "^2.0.0",
		"short-unique-id": "^3.0.4",
		"supertest-session": "^4.0.0",
		"typeorm": "^0.2.25",
		"typescript": "^3.9.7",
		"uuid": "^8.3.0"
	},
```
A few sentences describing the overall goals of the issue.

After builing my project using `tsc --project tsconfig.compile.json`
i get the below error when trying to create a new user. This doesn’t happen when running using npm start

The error occurs within my user service, as apparently the userRepository doesn't exist.
```bash
TypeError: Cannot read property 'save' of undefined
    at UserRepository.Repository.save (/Users/.../Server/dist/node_modules/typeorm/repository/Repository.js:78:29)
    at UserService.<anonymous> (/Users.../Server/dist/Services/Common/UserService.js:34:54)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/.../Server/dist/node_modules/tslib/tslib.js:110:62)
```

Configs:
```json
// tsconfig.compile.json
{
	"extends": "./tsconfig.json",
	"compilerOptions": {
		"baseUrl": ".",
		"outDir": "./dist",
		"moduleResolution": "node",
		"declaration": true,
		"noResolve": false,
		"preserveConstEnums": true,
		"sourceMap": true,
		"noEmit": false,
		"inlineSources": true
	},
	"include": ["./src/**/*.ts"]
}
```

```json
// tsconfig.json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es2016",
		"sourceMap": true,
		"declaration": false,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"moduleResolution": "node",
		"isolatedModules": false,
		"suppressImplicitAnyIndexErrors": false,
		"noImplicitAny": true,
		"strictNullChecks": true,
		"noUnusedLocals": false,
		"noUnusedParameters": false,
		"allowSyntheticDefaultImports": true,
		"importHelpers": true,
		"newLine": "LF",
		"noEmit": true,
		"resolveJsonModule": true,
		"lib": ["es7", "dom", "esnext.asynciterable"],
		"typeRoots": ["./node_modules/@types"]
	},
	"include": ["./src/**/*.ts", "./tests/**/**.ts"],
	"exclude": ["node_modules", "./public", "dist"],
	"linterOptions": {
		"exclude": []
	}
}
```
My user repository is
```typescript
import { EntityRepository, Repository } from 'typeorm';
import UserEntity from '../Entities/UserEntity';

@EntityRepository(UserEntity)
export default class UserRepository extends Repository<UserEntity> {
    // vibe
}
```

and my config file is
```typescript
/* istanbul ignore file */
process.env.NODE_ENV !== 'production'
	? require('dotenv').config({ path: '.env' })
	: () => {};
import * as Path from 'path';
import Controllers from '../Controllers/';
import Middleware from '../Middleware';
import Services from '../Services';
import cookies from './cookie.config';
import './extensions';
import typeorm from './typeorm.config';

export const rootDir = Path.resolve(__dirname, '../');
export default {
	rootDir,
	mount: {
		'/': Controllers,
	},
	componentsScan: [Services, Middleware],
	host: '127.0.0.1',
	port: process.env.SERVER_PORT,
	acceptMimes: ['application/json'],
	typeorm,
	cookies,
};
```

where typeorm config is
```typescript
/* istanbul ignore file */
import Entities from '../Database/Entities';
const TESTING = process.env.NODE_ENV === 'test';
export const DATABASE_NAME = TESTING
	? process.env.DB_TABLE + '_test'
	: process.env.DB_TABLE;

const SYNC = process.env.NODE_ENV !== 'production';

export default [
	{
		name: 'default',
		type: 'mysql',
		host: process.env.DB_HOST,
		username: process.env.DB_USER,
		password: process.env.DB_PASS,
		database: DATABASE_NAME,
		synchronize: SYNC,
		dropSchema: TESTING,
		entities: Entities,
	},
];
```

Any help or pointers would be awesome, I seem to keep running into trouble with TypeORM related issues :(

**Comment by Romakita** [comment]
Hello @bpofficial,

This issue means there is any connection associated to the repository. The userRepository exist but the connection is missing. I already seen this error but I don’t remember How i fixed that.

**Comment by Romakita** [comment]
@bpofficial Have you found the problem ?
