### ISSUE TITLE
[V5] [BUG] schema/swagger: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#934]
## Information

- **Version:** 5.65.3
- **Packages:** typescript": "4.0.3"

I updated from `5.52.1` to `5.65.3`. I added `@tsed/schema` for `5.65.3`.

I replaced from `AllowTypes` to `Any` decorator

**Previous**
```typescript
import { AllowTypes } from '@tsed/common';
// ...
export class MyClass {
  // ...
  @AllowTypes('number', 'null')
  public myId: number = -1; // default value
}
```
**Current**
```typescript
import { Any } from '@tsed/schema';
// ...
@Any('number', 'null')
public myId: number = -1; // default value
```

I use this class in `get` method:
```typescript
  @Get('/my-endpoint')
  public async getMyEndpoint(
    @QueryParams() params: MyClass,
  ) {
// ...
```

I replaced them on more than 100 places.
But it seems only one field doesn't work. Now I get error while server is starting:
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at serializeModelToParameter (\node_modules\@tsed\swagger\src\class\OpenApiParamsBuilder.ts:10:17)
    at OpenApiParamsBuilder.createSchemaFromQueryParam (\node_modules\@tsed\swagger\src\class\OpenApiParamsBuilder.ts:132:14)
    at injectedParams.filter.reduce (\node_modules\@tsed\swagger\src\class\OpenApiParamsBuilder.ts:285:19)
    at Array.reduce (<anonymous>)
    at OpenApiParamsBuilder.getInQueryParams (\node_modules\@tsed\swagger\src\class\OpenApiParamsBuilder.ts:278:8)
    at OpenApiParamsBuilder.build (\node_modules\@tsed\swagger\src\class\OpenApiParamsBuilder.ts:60:98)
    at utils_1.parseSwaggerPath.forEach (\node_modules\@tsed\swagger\src\class\OpenApiEndpointBuilder.ts:38:117)
    at Array.forEach (<anonymous>)
    at OpenApiEndpointBuilder.build (\node_modules\@tsed\swagger\src\class\OpenApiEndpointBuilder.ts:37:62)
    at endpoint.pathsMethods.forEach (\node_modules\@tsed\swagger\src\services\SwaggerService.ts:144:105)
    at Array.forEach (<anonymous>)
    at ctrl.endpoints.forEach (\node_modules\@tsed\swagger\src\services\SwaggerService.ts:141:29)
    at Array.forEach (<anonymous>)
    at SwaggerService.buildRoutes (\node_modules\@tsed\swagger\src\services\SwaggerService.ts:136:20)
    at platform.routes.forEach (\node_modules\@tsed\swagger\src\services\SwaggerService.ts:35:33)
```

**Comment by Romakita** [comment]
Hello @silveoj 
You mustn't use `@Any` from  @tsed/schema but from "@tsed/common" with the v5 version. Replace all @tsed/schema by @tsed/common :) It should solve your issue!

See you
romain

**Comment by silveoj** [comment]
Thanks. Ir works. Close it)
Maybe change description in source code `@tsed\common\lib\jsonschema\decorators\allowTypes.d.ts`:
```For v6 user, use @@Any@@ from @tsed/schema instead of @@AllowTypes@@ from @tsed/common.```

**Comment by silveoj** [comment]
Thanks. It works. Close it)
Maybe change description in source code `@tsed\common\lib\jsonschema\decorators\allowTypes.d.ts`:
```For v6 user, use @@Any@@ from @tsed/schema instead of @@AllowTypes@@ from @tsed/common.```

**Comment by Romakita** [comment]
It's only for v6 :)
