### ISSUE TITLE
[BUG] yarn test failed on Windows

### ISSUE THREAD

**Issue by rluvaton** [TypedProject/tsed#953]
## Information

- **Version:** 5.65.4
- Packages: 

A few sentences describing the overall goals of the issue.

This is the output for `yarn test`

```
C:\tsed>yarn test
yarn run v1.15.2
$ yarn clean && yarn test:lint && yarn test:coverage
$ monorepo clean workspace
  √ Clean workspace
$ tslint --project tsconfig.json -e examples
$ cross-env NODE_ENV=test nyc mocha


  ..........................................................................................................................
  ......................................................(node:16560) DeprecationWarning: @Property(options) is deprecated. Use @Name() or/and @CollectionOf() instead
.(node:16560) DeprecationWarning: @Property(name: string) are deprecated. Use @Name() instead
...................................................................
  ................................(node:16560) DeprecationWarning: UseFilter is deprecated. Use UseParam instead
.(node:16560) DeprecationWarning: UseFilter is deprecated. Use UseParam instead
.........................................................................................
  .....................(node:16560) DeprecationWarning: $onInit hook is deprecated. Use $beforeInit instead
!(node:16560) DeprecationWarning: $onInit hook is deprecated. Use $beforeInit instead
.(node:16560) DeprecationWarning: $onInit hook is deprecated. Use $beforeInit instead
...................................(node:16560) DeprecationWarning: Use ServerLoader.addControllers instead
(node:16560) DeprecationWarning: $onInit hook is deprecated. Use $beforeInit instead
(node:16560) DeprecationWarning: $onMountingMiddlewares hook is deprecated. Use $beforeRoutesInit instead
.........(node:16560) DeprecationWarning: $onInit hook is deprecated. Use $beforeInit instead
(node:16560) DeprecationWarning: $onMountingMiddlewares hook is deprecated. Use $beforeRoutesInit instead
(node:16560) DeprecationWarning: Use ServerLoader.addControllers or ServerLoader.addComponents instead
.......................................................
  ..........................................................................................................................
  ..........................................................................................................................
  ..........................................................................................................................
  ..............................................(node:16560) DeprecationWarning: interceptor.aroundInvoke is deprecated. Use interceptor.intercept instead.
(node:16560) DeprecationWarning: context.proceed() is deprecated. Use context.next() or next() parameters instead.
............................................................................
  ...................................................................................................(node:16560) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
.......................
  .............................................................................................!............................
  ..........................................................................................................................
  ..........................................................................................................................
  ..........................................................................................................................
  ...............................................................................

  1663 passing (32s)
  2 failing

  1) PlatformBuilder
       addComponents
         should add components:

      AssertionError: expected [ Array(5) ] to deeply equal [ Array(5) ]
      + expected - actual

       [
      -  "C:\\tsed/mvc/**/*.ts"
      -  "C:\\tsed/services/**/*.ts"
      -  "C:\\tsed/middlewares/**/*.ts"
      -  "C:\\tsed/converters/**/*.ts"
      +  "C:\\tsed\\mvc\\**\\*.ts"
      +  "C:\\tsed\\services\\**\\*.ts"
      +  "C:\\tsed\\middlewares\\**\\*.ts"
      +  "C:\\tsed\\converters\\**\\*.ts"
         [Function]
       ]

      at Context.<anonymous> (packages\common\src\platform-builder\builder\PlatformBuilder.spec.ts:152:63)

  2) PlatformExpress
       View
         Scenario1: GET /rest/views/scenario-1
           should render a view:

      AssertionError: expected '<p>Hello world with opts and ID local-10909</p>\r\n' to deeply equal '<p>Hello world with opts and ID local-10909</p>\n'
      + expected - actual

      -<p>Hello world with opts and ID local-10909</p>
      +<p>Hello world with opts and ID local-10909</p>

      at Context.<anonymous> (packages\platform-test-utils\src\tests\testView.ts:54:37)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)




=============================== Coverage summary ===============================
Statements   : 99.78% ( 6914/6929 )
Branches     : 88.29% ( 2962/3355 )
Functions    : 99.68% ( 1848/1854 )
Lines        : 99.78% ( 6661/6676 )
================================================================================
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by rluvaton** [comment]
@Romakita I'm on it

**Comment by Romakita** [comment]
#954 Merged :)
